/**
 * Generates the lucide icon geometry and the third-party notice from the installed lucide-react.
 *
 *   pnpm icons:generate          write both files
 *
 * `build()` is also called by `test/icon-sets/generated.test.ts`, which fails when the committed
 * files differ from a fresh build (same idea as `pnpm schema:generate`).
 */
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import { format } from 'prettier';

import { CHROME_ICONS } from '../src/icon-sets/chrome-icons';
import { LUCIDE_CATALOG } from '../src/icon-sets/lucide-catalog';

// dirname, not new URL(import.meta.url): vitest imports this file under a non-file URL.
const root = `${resolve(import.meta.dirname, '..')}/`;
const lucideDir = `${root}node_modules/lucide-react/`;

export const GENERATED_PATH = `${root}src/icon-sets/lucide.generated.ts`;
export const NOTICES_PATH = resolve(root, '../../apps/app/public/third-party-notices.txt');

interface IconData {
  node: readonly (readonly [string, Record<string, unknown>])[];
  aliases?: readonly string[];
}

async function readIcon(name: string): Promise<IconData> {
  const file = `${lucideDir}dist/esm/icons/${name}.mjs`;
  const mod = (await import(pathToFileURL(file).href).catch(() => null)) as {
    __iconData?: IconData;
  } | null;
  if (!mod?.__iconData) throw new Error(`lucide icon not found in the installed package: ${name}`);
  return mod.__iconData;
}

/** The generated geometry module and the notices text, both as they should be on disk. */
export async function build(): Promise<{ generated: string; notices: string }> {
  const pkg = JSON.parse(await readFile(`${lucideDir}package.json`, 'utf8')) as { version: string };
  const names = [
    ...new Set([...LUCIDE_CATALOG.map((e) => e.name), ...Object.values(CHROME_ICONS)]),
  ].toSorted();

  const entries: string[] = [];
  for (const name of names) {
    const data = await readIcon(name);
    // `key` is React bookkeeping, not geometry.
    const node = data.node.map(([tag, attrs]) => [
      tag,
      Object.fromEntries(Object.entries(attrs).filter(([k]) => k !== 'key')),
    ]);
    entries.push(
      `${JSON.stringify(name)}: { node: ${JSON.stringify(node)}, aliases: ${JSON.stringify(data.aliases ?? [])} },`,
    );
  }

  const raw = `// GENERATED by pnpm icons:generate from lucide-react ${pkg.version}. Do not edit.
import type { IconNode } from './types';

export const LUCIDE_VERSION = ${JSON.stringify(pkg.version)};

export const LUCIDE_GEOMETRY: Readonly<
  Record<string, { node: IconNode; aliases: readonly string[] }>
> = {
${entries.join('\n')}
};
`;
  const generated = await format(raw, { parser: 'typescript', singleQuote: true, printWidth: 100 });
  const licence = await readFile(`${lucideDir}LICENSE`, 'utf8');
  const notices = `lucide-react ${pkg.version} (ISC)\n\n${licence}`;
  return { generated, notices };
}

// TODO(open-source): link third-party-notices.txt from the app once the licence page is decided.
if (process.argv[1]?.endsWith('generate-icons.ts')) {
  const { generated, notices } = await build();
  await writeFile(GENERATED_PATH, generated);
  await writeFile(NOTICES_PATH, notices);
  console.log(`Wrote ${GENERATED_PATH}\nWrote ${NOTICES_PATH}`);
}
