import type { ProblemKind } from '@sododeck/model';
import {
  Ban,
  Columns3,
  Copy,
  CopyX,
  Fingerprint,
  KeyRound,
  Link2Off,
  List,
  ListX,
  Maximize2,
  Network,
  Package,
  Repeat,
  Shapes,
  Split,
  Table2,
  TextCursorInput,
  Unplug,
  Workflow,
  Waypoints,
  type LucideIcon,
} from 'lucide-react';

export const problemCountLabel = (count: number) =>
  count === 1 ? '1 problem' : `${String(count)} problems`;

/** Icon of a problem row, by kind (design 60). */
export const PROBLEM_ICONS: Record<ProblemKind, LucideIcon> = {
  'duplicate-connection': Copy,
  'step-without-connection': Unplug,
  'broken-chain': Workflow,
  'incomplete-flow': Workflow,
  'overlapping-conditions': Split,
  'missing-rule': Table2,
  'rule-without-catch-all': Table2,
  'invalid-rule-cells': Table2,
  'broken-reference': Link2Off,
  'card-size-out-of-range': Maximize2,
  'unknown-card-type': Shapes,
  'unknown-pack': Package,
  'field-value-dangling': ListX,
  'db-dangling-reference': Columns3,
  'db-composite-mismatch': KeyRound,
  'db-no-primary-key': Fingerprint,
  'db-duplicate-table': CopyX,
  'db-duplicate-column': CopyX,
  'db-duplicate-index': CopyX,
  'db-duplicate-enum': CopyX,
  'db-empty-column': TextCursorInput,
  'db-type-mismatch': Unplug,
  'db-null-default': Ban,
  'db-fk-not-key': KeyRound,
  'db-many-to-many': Network,
  'db-empty-enum': List,
  'db-default-type': ListX,
  'db-required-loop': Repeat,
  'db-duplicate-relationship': Waypoints,
  'db-unknown-type': Shapes,
};
