/**
 * The `.sododeck.md` form of a deck (070, contract `specs/070-obsidian-plugin/contracts/
 * markdown-form.md`, ADR 0051): the same canonical deck JSON wrapped in a Markdown note, with the
 * deck's titles and prose mirrored as readable text so a notes app can search and link them, and
 * edits to that text read back by stable id. Text in, text out: no Yjs, no I/O, and no Markdown
 * parser (a small line grammar we own, so text outside the owned region is copied byte for byte).
 */
import { checkPicturePath, emptySododeckFile } from '@sododeck/schema';

import { isRecord } from './is-record';
import { canonicalize } from './key-order';
import { frontOf, isDeckMarkdown, MARKER_KEY, MARKER_LINE, MARKER_VALUE } from './markdown-marker';
import { MD_PROBLEMS, type MdProblemCode } from './markdown-problems';
import type { ProblemEntry } from './report-json';

const BEGIN = '%% sododeck:begin';
const BEGIN_LINE = `${BEGIN} — generated by Sododeck; edit titles and notes, not the marker comments %%`;
const END_LINE = '%% sododeck:end %%';
const DATA_OPEN = '%% sododeck:data';
const UNNAMED = '(unnamed)';

export { isDeckMarkdown, MARKER_KEY, MARKER_VALUE };

export type FromMarkdown =
  { ok: true; deckText: string; edited: boolean } | { ok: false; entries: ProblemEntry[] };

// ---------------------------------------------------------------------------------------------
// The readable part: which titles and prose fields are mirrored (contract table). One constant
// drives the writer, the reader and the schema-sync test.
// ---------------------------------------------------------------------------------------------

/** A prose field written under `%%<id>:<field>%%`. */
export interface ReadableBody {
  field: string;
  /** An empty value is invalid (a sticky without text), so emptying it is ignored on read. */
  required?: boolean;
}

export interface ReadableKind {
  /** The `TEXT_FIELDS` kind these fields belong to (`text-fields.ts`). */
  textKind: string;
  /** Where the objects are: a top-level array, a map, or `steps` inside each flow. */
  collection:
    | 'deck'
    | 'nodes'
    | 'groups'
    | 'edges'
    | 'features'
    | 'flows'
    | 'steps'
    | 'rules'
    | 'stickies'
    | 'views';
  section: string | null;
  level: number;
  /** The field shown as the heading text; `null` for objects with a fixed heading. */
  title: string | null;
  titleRequired: boolean;
  /** Heading text when the object has no title (or no title field). */
  fixedTitle?: string;
  bodies: readonly ReadableBody[];
}

export const READABLE_FIELDS: readonly ReadableKind[] = [
  {
    textKind: 'meta',
    collection: 'deck',
    section: null,
    level: 1,
    title: 'name',
    titleRequired: false,
    bodies: [{ field: 'description' }],
  },
  {
    textKind: 'nodes',
    collection: 'nodes',
    section: 'Components',
    level: 3,
    title: 'title',
    titleRequired: true,
    bodies: [{ field: 'description' }],
  },
  {
    textKind: 'groups',
    collection: 'groups',
    section: 'Groups',
    level: 3,
    title: 'title',
    titleRequired: true,
    bodies: [{ field: 'description' }],
  },
  {
    textKind: 'edges',
    collection: 'edges',
    section: 'Connections',
    level: 3,
    title: 'label',
    titleRequired: false,
    bodies: [{ field: 'description' }],
  },
  {
    textKind: 'features',
    collection: 'features',
    section: 'Features',
    level: 3,
    title: 'title',
    titleRequired: true,
    bodies: [{ field: 'description' }],
  },
  {
    textKind: 'flows',
    collection: 'flows',
    section: 'Flows',
    level: 3,
    title: 'title',
    titleRequired: true,
    bodies: [{ field: 'description' }],
  },
  {
    textKind: 'step',
    collection: 'steps',
    section: null,
    level: 4,
    title: 'title',
    titleRequired: false,
    bodies: [{ field: 'description' }, { field: 'notes' }],
  },
  {
    textKind: 'rule',
    collection: 'rules',
    section: 'Rules',
    level: 3,
    title: 'title',
    titleRequired: true,
    bodies: [{ field: 'description' }],
  },
  {
    textKind: 'stickies',
    collection: 'stickies',
    section: 'Notes',
    level: 3,
    title: null,
    titleRequired: false,
    fixedTitle: 'Note',
    bodies: [{ field: 'text', required: true }],
  },
  {
    textKind: 'views',
    collection: 'views',
    section: 'Views',
    level: 3,
    title: 'title',
    titleRequired: true,
    bodies: [],
  },
];

/**
 * Long-text fields the form deliberately leaves in the deck block only, with the reason. A schema
 * test requires every `TEXT_FIELDS` entry to be either in {@link READABLE_FIELDS} or here.
 */
export const READABLE_IGNORED: readonly { textKind: string; field: string; reason: string }[] = [
  {
    textKind: 'step',
    field: 'payload',
    reason: 'a message body or code sample, not prose to search',
  },
  {
    textKind: 'branch',
    field: 'description',
    reason: 'branches have no heading of their own in the note',
  },
];

const SECTION_HEADINGS = new Set([
  ...READABLE_FIELDS.flatMap((k) => (k.section === null ? [] : [k.section])),
  'Pictures',
]);

// ---------------------------------------------------------------------------------------------
// Escaping. One pass each way over a small token table, so the reverse is exact:
//   `%%` ↔ `%&#37;`   `<br>` (written for a line break in a title) ↔ `\n`
//   a literal `<br>` ↔ `&lt;br>`   an `&` that would start one of these tokens ↔ `&amp;`
// ---------------------------------------------------------------------------------------------

const ESCAPE = /%%|\n|<br>|&(?=(?:amp;)*(?:#37;|lt;br>))/g;
const UNESCAPE = /%&#37;|<br>|&lt;br>|&amp;((?:amp;)*(?:#37;|lt;br>))/g;

function escapeText(text: string, lineBreak: '<br>' | '\n'): string {
  return text.replace(ESCAPE, (token) => {
    if (token === '%%') return '%&#37;';
    if (token === '\n') return lineBreak;
    if (token === '<br>') return '&lt;br>';
    return '&amp;';
  });
}

function unescapeText(text: string, breakToNewline: boolean): string {
  return text.replace(UNESCAPE, (token, rest: string | undefined) => {
    if (token === '%&#37;') return '%%';
    if (token === '<br>') return breakToNewline ? '\n' : token;
    if (token === '&lt;br>') return '<br>';
    return `&${rest ?? ''}`;
  });
}

const encodeTitle = (title: string): string => escapeText(title.replace(/\r\n?/g, '\n'), '<br>');
const decodeTitle = (text: string): string => unescapeText(text, true).trim();

/** A body line that would read as a heading gets a backslash in front of its first `#`. */
function encodeBody(body: string): string[] {
  return escapeText(body.replace(/\r\n?/g, '\n'), '\n')
    .split('\n')
    .map((line) => line.replace(/^(\s*)(\\*)#/, '$1$2\\#'));
}

function decodeBody(lines: readonly string[]): string {
  const raw = lines.map((line) => line.replace(/^(\s*)\\(\\*#)/, '$1$2'));
  let start = 0;
  let end = raw.length;
  while (start < end && (raw[start] ?? '').trim() === '') start++;
  while (end > start && (raw[end - 1] ?? '').trim() === '') end--;
  return unescapeText(raw.slice(start, end).join('\n'), false);
}

/** What reading back gives for `value` as written: edits are real only when they differ from it. */
const settledTitle = (value: string): string => decodeTitle(encodeTitle(value));
const settledBody = (value: string): string => decodeBody(encodeBody(value));

// ---------------------------------------------------------------------------------------------
// Targets: every object the readable part mirrors, in writing order, with get/set on the deck.
// ---------------------------------------------------------------------------------------------

type Json = Record<string, unknown>;

interface Target {
  id: string;
  kind: ReadableKind;
  object: Json;
  /** Child targets that follow this one (a flow's steps). */
  children: Target[];
}

const KIND = Object.fromEntries(READABLE_FIELDS.map((k) => [k.collection, k])) as Record<
  ReadableKind['collection'],
  ReadableKind
>;

function objectsOf(value: unknown): Json[] {
  return Array.isArray(value) ? value.filter(isRecord) : [];
}

function idOf(object: Json): string | undefined {
  return typeof object.id === 'string' && object.id !== '' && !/[\s%]/.test(object.id)
    ? object.id
    : undefined;
}

function sectionsOf(
  deck: Json,
): { section: string | null; kind: ReadableKind; targets: Target[] }[] {
  const make = (kind: ReadableKind, objects: Json[], keyed?: [string, Json][]): Target[] => {
    const out: Target[] = [];
    const items: [string | undefined, Json][] = keyed ?? objects.map((o) => [idOf(o), o]);
    for (const [id, object] of items) {
      if (id === undefined || /[\s%:]/.test(id) || id === '') continue;
      const children = kind.collection === 'flows' ? make(KIND.steps, objectsOf(object.steps)) : [];
      out.push({ id, kind, object, children });
    }
    return out;
  };
  const rules: [string, Json][] = isRecord(deck.rules)
    ? Object.entries(deck.rules).flatMap(([id, rule]): [string, Json][] =>
        isRecord(rule) ? [[id, rule]] : [],
      )
    : [];
  return [
    { section: 'Components', kind: KIND.nodes, targets: make(KIND.nodes, objectsOf(deck.nodes)) },
    { section: 'Groups', kind: KIND.groups, targets: make(KIND.groups, objectsOf(deck.groups)) },
    { section: 'Connections', kind: KIND.edges, targets: make(KIND.edges, objectsOf(deck.edges)) },
    {
      section: 'Features',
      kind: KIND.features,
      targets: make(KIND.features, objectsOf(deck.features)),
    },
    { section: 'Flows', kind: KIND.flows, targets: make(KIND.flows, objectsOf(deck.flows)) },
    { section: 'Rules', kind: KIND.rules, targets: make(KIND.rules, [], rules) },
    {
      section: 'Notes',
      kind: KIND.stickies,
      targets: make(KIND.stickies, objectsOf(deck.stickies)),
    },
    { section: 'Views', kind: KIND.views, targets: make(KIND.views, objectsOf(deck.views)) },
  ];
}

function titleOf(target: Target): string {
  const { kind, object } = target;
  if (kind.title === null) return kind.fixedTitle ?? '';
  const value = object[kind.title];
  return typeof value === 'string' ? value : '';
}

// ---------------------------------------------------------------------------------------------
// Parsing the file: front matter, user text, the owned region, the units inside it.
// ---------------------------------------------------------------------------------------------

interface Split {
  /** Front matter including its fences and the BOM, or `''`. */
  front: string;
  /** Text between the front matter and the region start (or the whole body when no region). */
  before: string;
  /** Region lines between the begin and end lines, exclusive; `null` when there is no region. */
  region: string[] | null;
  /** Text after the end line, verbatim. */
  after: string;
}

function splitFile(text: string): Split {
  const front = frontOf(text)?.raw ?? '';
  const rest = text.slice(front.length);
  const lines = rest.split('\n');
  const begin = lines.findIndex((l) => l.startsWith(BEGIN));
  if (begin < 0) return { front, before: rest, region: null, after: '' };
  let end = lines.findIndex((l, i) => i > begin && l.trimEnd() === END_LINE);
  if (end < 0) end = lines.length;
  return {
    front,
    before: begin === 0 ? '' : `${lines.slice(0, begin).join('\n')}\n`,
    region: lines.slice(begin + 1, end).map((l) => l.replace(/\r$/, '')),
    after: end >= lines.length ? '' : lines.slice(end + 1).join('\n'),
  };
}

type Unit =
  | { kind: 'text'; lines: string[] }
  | { kind: 'heading'; level: number; text: string; id: string | null; lines: string[] }
  | { kind: 'body'; id: string; field: string; lines: string[] }
  | { kind: 'picture'; id: string; link: string | null; line: string }
  | { kind: 'data'; text: string | null };

const HEADING = /^(#{1,6})[ \t]+(.*?)[ \t]*$/;
const HEADING_ID = /^(.*?)[ \t]*%%([^\s%]+)%%$/;
const BODY_MARKER = /^%%([^\s%:]+):([A-Za-z]+)%%[ \t]*$/;
const PICTURE_LINE = /^- (.*) %%([0-9a-f]{64})%%[ \t]*$/;
const LINK = /^\[\[(.*)\]\]$/;

function parseRegion(lines: readonly string[]): Unit[] {
  const units: Unit[] = [];
  let current: Unit = { kind: 'text', lines: [] };
  units.push(current);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? '';
    if (line.trimEnd() === DATA_OPEN) {
      const open = /^(`{3,})json[ \t]*$/.exec(lines[i + 1] ?? '');
      if (open === null) {
        units.push({ kind: 'data', text: null });
        current = { kind: 'text', lines: [] };
        units.push(current);
        continue;
      }
      const fence = open[1] ?? '```';
      const body: string[] = [];
      let j = i + 2;
      while (j < lines.length && (lines[j] ?? '').trim() !== fence) body.push(lines[j++] ?? '');
      j++; // the closing fence
      if ((lines[j] ?? '').trim() === '%%') j++;
      units.push({ kind: 'data', text: body.join('\n') });
      current = { kind: 'text', lines: [] };
      units.push(current);
      i = j - 1;
      continue;
    }
    const heading = HEADING.exec(line);
    if (heading !== null) {
      const raw = heading[2] ?? '';
      const marked = HEADING_ID.exec(raw);
      current = {
        kind: 'heading',
        level: (heading[1] ?? '#').length,
        text: marked === null ? raw : (marked[1] ?? ''),
        id: marked === null ? null : (marked[2] ?? null),
        lines: [],
      };
      units.push(current);
      continue;
    }
    const body = BODY_MARKER.exec(line);
    if (body !== null) {
      current = { kind: 'body', id: body[1] ?? '', field: body[2] ?? '', lines: [] };
      units.push(current);
      continue;
    }
    const picture = PICTURE_LINE.exec(line);
    if (picture !== null) {
      const link = LINK.exec(picture[1] ?? '');
      units.push({ kind: 'picture', id: picture[2] ?? '', link: link?.[1] ?? null, line });
      current = { kind: 'text', lines: [] };
      units.push(current);
      continue;
    }
    current.lines.push(line);
  }
  return units;
}

const isBlank = (lines: readonly string[]): boolean => lines.every((l) => l.trim() === '');

// ---------------------------------------------------------------------------------------------
// Foreign blocks: headings and text in the old region that no marker explains. Kept after the
// marked item they followed (the top of the region when they followed none).
// ---------------------------------------------------------------------------------------------

function foreignBlocks(region: readonly string[] | null): Map<string | null, string[][]> {
  const out = new Map<string | null, string[][]>();
  if (region === null) return out;
  let anchor: string | null = null;
  let open: string[] | null = null;
  const add = (lines: string[]): void => {
    const list = out.get(anchor) ?? [];
    list.push(trimBlankEnds(lines));
    out.set(anchor, list);
  };
  const close = (): void => {
    if (open !== null && !isBlank(open)) add(open);
    open = null;
  };
  for (const unit of parseRegion(region)) {
    if (unit.kind === 'text') {
      if (open !== null) open.push(...unit.lines);
      else if (!isBlank(unit.lines)) {
        open = [...unit.lines];
      }
      continue;
    }
    if (unit.kind === 'heading') {
      close();
      if (unit.id !== null) {
        anchor = unit.id;
        // Text right under a heading, before any marker line, is kept right under it.
        if (!isBlank(unit.lines)) {
          const list = out.get(`tail:${unit.id}`) ?? [];
          list.push(trimBlankEnds(unit.lines));
          out.set(`tail:${unit.id}`, list);
        }
      } else if (unit.level === 2 && SECTION_HEADINGS.has(unit.text)) {
        // generated section heading: regenerated, never kept
      } else {
        const raw = `${'#'.repeat(unit.level)} ${unit.text}`;
        open = [raw, ...unit.lines];
      }
      continue;
    }
    close();
    if (unit.kind === 'body') anchor = unit.id;
  }
  close();
  return out;
}

function trimBlankEnds(lines: string[]): string[] {
  let start = 0;
  let end = lines.length;
  while (start < end && (lines[start] ?? '').trim() === '') start++;
  while (end > start && (lines[end - 1] ?? '').trim() === '') end--;
  return lines.slice(start, end);
}

// ---------------------------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------------------------

function fenceFor(text: string): string {
  let longest = 0;
  for (const run of text.match(/`+/g) ?? []) longest = Math.max(longest, run.length);
  return '`'.repeat(Math.max(3, longest + 1));
}

function headingLine(level: number, title: string, id: string): string {
  return `${'#'.repeat(level)} ${title} %%${id}%%`;
}

function emitTarget(target: Target, out: string[], foreign: Map<string | null, string[][]>): void {
  const { kind, id, object } = target;
  const text = titleOf(target);
  const title =
    kind.title === null
      ? (kind.fixedTitle ?? '')
      : text.trim() === ''
        ? UNNAMED
        : encodeTitle(text);
  out.push(headingLine(kind.level, title, id), '');
  emitForeign(`tail:${id}`, out, foreign);
  for (const body of kind.bodies) {
    const value = object[body.field];
    if (typeof value !== 'string') continue;
    out.push(`%%${id}:${body.field}%%`, ...encodeBody(value), '');
  }
  for (const child of target.children) emitTarget(child, out, foreign);
  emitForeign(id, out, foreign);
}

function emitForeign(
  anchor: string | null,
  out: string[],
  foreign: Map<string | null, string[][]>,
): void {
  for (const block of foreign.get(anchor) ?? []) out.push(...block, '');
}

function pictureLines(deck: Json): string[] {
  const assets = isRecord(deck.assets) ? deck.assets : {};
  const lines: string[] = [];
  for (const [id, asset] of Object.entries(assets)) {
    if (!isRecord(asset) || !/^[0-9a-f]{64}$/.test(id)) continue;
    const path = typeof asset.path === 'string' ? asset.path : undefined;
    const name = typeof asset.name === 'string' && asset.name !== '' ? asset.name : id.slice(0, 8);
    // A link the notes app would parse differently from the path (or that is not a link at all)
    // is written as a plain name; the deck block keeps the path.
    if (path !== undefined && path !== '' && !/[[\]|#^%\n\r]/.test(path)) {
      lines.push(`- [[${path}]] %%${id}%%`);
    } else {
      lines.push(`- ${encodeTitle(name)} %%${id}%%`);
    }
  }
  return lines;
}

function ensureMarker(front: string): string {
  if (front === '') return `---\n${MARKER_KEY}: ${MARKER_VALUE}\n---\n`;
  if (MARKER_LINE.test(front)) return front;
  const keyed = new RegExp(`^${MARKER_KEY}:.*$`, 'm');
  if (keyed.test(front)) return front.replace(keyed, `${MARKER_KEY}: ${MARKER_VALUE}`);
  const eol = front.includes('\r\n') ? '\r\n' : '\n';
  return front.replace(/^(\uFEFF?---[ \t]*\r?\n)/, `$1${MARKER_KEY}: ${MARKER_VALUE}${eol}`);
}

/**
 * Wrap canonical deck JSON (what `serializeDeck` returns) as a `.sododeck.md` note. `previous` is
 * the last file text read or written: text outside the owned region, other front matter keys and
 * foreign blocks inside it are copied from it. Throws when `deckText` is not JSON (the editor only
 * ever sends the text of a deck it holds).
 */
export function toMarkdown(deckText: string, previous?: string): string {
  const parsed: unknown = JSON.parse(deckText.startsWith('\uFEFF') ? deckText.slice(1) : deckText);
  if (!isRecord(parsed)) throw new Error('A deck is a JSON object.');
  const deck = parsed;
  const prev = previous === undefined ? undefined : splitFile(previous);
  const foreign = foreignBlocks(prev?.region ?? null);

  const out: string[] = [BEGIN_LINE];
  const name =
    typeof deck.name === 'string' && deck.name.trim() !== '' ? encodeTitle(deck.name) : UNNAMED;
  // Text before the first heading stays before it (after the first heading it would read as the
  // deck description).
  emitForeign(null, out, foreign);
  out.push(headingLine(1, name, 'deck'), '');
  emitForeign('tail:deck', out, foreign);
  if (typeof deck.description === 'string') {
    out.push('%%deck:description%%', ...encodeBody(deck.description), '');
  }
  emitForeign('deck', out, foreign);
  for (const { section, targets } of sectionsOf(deck)) {
    if (targets.length === 0) continue;
    out.push(`## ${section}`, '');
    for (const target of targets) emitTarget(target, out, foreign);
  }
  const pictures = pictureLines(deck);
  if (pictures.length > 0) out.push('## Pictures', '', ...pictures, '');

  const json = JSON.stringify(parsed, null, 2).replace(/%%/g, '%\\u0025');
  const fence = fenceFor(json);
  out.push(DATA_OPEN, `${fence}json`, json, fence, '%%', END_LINE);

  const front = ensureMarker(prev?.front ?? '');
  const before = prev?.before ?? '';
  return `${front}${before}${out.join('\n')}\n${prev?.after ?? ''}`;
}

// ---------------------------------------------------------------------------------------------
// Reading
// ---------------------------------------------------------------------------------------------

function failure(code: MdProblemCode): FromMarkdown {
  const problem = MD_PROBLEMS[code];
  return {
    ok: false,
    entries: [{ code, severity: 'error', message: problem.message, fix: problem.fix }],
  };
}

const canonicalText = (value: unknown): string =>
  `${JSON.stringify(canonicalize(value), null, 2)}\n`;

/** The canonical text of an empty deck: what a marker-only note or an empty file opens as. */
export const emptyDeckText = (): string => canonicalText(emptySododeckFile());

function bodyTargets(deck: Json): Map<string, Target[]> {
  const byId = new Map<string, Target[]>();
  const add = (target: Target): void => {
    byId.set(target.id, [...(byId.get(target.id) ?? []), target]);
    target.children.forEach(add);
  };
  add({ id: 'deck', kind: KIND.deck, object: deck, children: [] });
  for (const { targets } of sectionsOf(deck)) targets.forEach(add);
  return byId;
}

/**
 * Read a `.sododeck.md` note back to deck JSON. Lenient about everything except the deck block: it
 * never validates the deck (the editor and `inspectDeckText` do). `edited` is true when at least
 * one title, notes value or picture link in the readable part differs from the block.
 */
export function fromMarkdown(markdown: string): FromMarkdown {
  const text = markdown.startsWith('\uFEFF') ? markdown.slice(1) : markdown;
  if (!isDeckMarkdown(text)) return failure('md-no-marker');
  const { region } = splitFile(text);
  if (region === null)
    return { ok: true, deckText: canonicalText(emptySododeckFile()), edited: false };

  const units = parseRegion(region);
  const blocks = units.filter((u) => u.kind === 'data');
  if (blocks.length === 0) return failure('md-no-deck-block');
  if (blocks.length > 1) return failure('md-two-deck-blocks');
  const block = blocks[0];
  let deck: unknown;
  try {
    deck = block?.kind === 'data' && block.text !== null ? JSON.parse(block.text) : undefined;
  } catch {
    return failure('md-deck-block-not-json');
  }
  if (!isRecord(deck)) return failure('md-deck-block-not-json');

  const edited = applyReadable(deck, units);
  return { ok: true, deckText: canonicalText(deck), edited };
}

/** Applies title, prose and picture-link edits by id; returns whether any value changed. */
function applyReadable(deck: Json, units: readonly Unit[]): boolean {
  const targets = bodyTargets(deck);
  const used = new Map<string, number>();
  const take = (id: string): Target | undefined => {
    const list = targets.get(id);
    if (list === undefined) return undefined;
    const n = used.get(id) ?? 0;
    return list[Math.min(n, list.length - 1)];
  };
  // Duplicate ids (rare) are matched in writing order: the nth heading with an id is its nth target.
  const advance = (id: string): void => {
    used.set(id, (used.get(id) ?? 0) + 1);
  };
  let edited = false;
  const seenBody = new Set<string>();

  for (const unit of units) {
    if (unit.kind === 'heading' && unit.id !== null) {
      const target = take(unit.id);
      advance(unit.id);
      if (target === undefined) continue;
      seenBody.clear();
      const field = target.kind.title;
      if (field === null) continue;
      const value = decodeTitle(unit.text);
      const current = typeof target.object[field] === 'string' ? target.object[field] : '';
      if (value === '') continue;
      const settled =
        current.trim() === '' && target.kind.title !== null ? UNNAMED : settledTitle(current);
      if (value === settled) continue;
      target.object[field] = value;
      edited = true;
    } else if (unit.kind === 'body') {
      // The body belongs to the target of the most recent heading with this id.
      const list = targets.get(unit.id);
      if (list === undefined) continue;
      const n = Math.max(0, (used.get(unit.id) ?? 1) - 1);
      const target = list[Math.min(n, list.length - 1)];
      const spec = target?.kind.bodies.find((b) => b.field === unit.field);
      if (target === undefined || spec === undefined) continue;
      const key = `${unit.id}:${unit.field}:${String(n)}`;
      if (seenBody.has(key)) continue;
      seenBody.add(key);
      const value = decodeBody(unit.lines);
      const current = target.object[spec.field];
      const was = typeof current === 'string' ? current : undefined;
      if (value === (was === undefined ? '' : settledBody(was))) continue;
      if (value === '') {
        if (spec.required === true) continue;
        Reflect.deleteProperty(target.object, spec.field);
      } else {
        target.object[spec.field] = value;
      }
      edited = true;
    } else if (unit.kind === 'picture' && unit.link !== null) {
      const assets = isRecord(deck.assets) ? deck.assets : {};
      const asset = assets[unit.id];
      if (!isRecord(asset) || typeof asset.path !== 'string') continue;
      const link = unit.link.replace(/[|#].*$/, '').trim();
      if (link === '' || link === asset.path || checkPicturePath(link) !== null) continue;
      asset.path = link;
      edited = true;
    }
  }
  return edited;
}
