-- Edge cases · Edge DB · Postgres
-- Generated by Sododeck. Notes: 13

CREATE SCHEMA IF NOT EXISTS billing;

CREATE TABLE categories (
  id integer PRIMARY KEY
);

CREATE TABLE keyless (
  v integer
);

CREATE TYPE empty_choice AS ENUM ();

-- `money` kept as written: not in the common type list for Postgres
-- misc.blank has no type; written as text
-- misc.code: auto-increment needs an integer type in Postgres; dropped
CREATE TABLE misc (
  id integer PRIMARY KEY,
  blank text,
  empty_choice empty_choice,
  code text,
  data jsonb,
  price money,
  label varchar,
  flag boolean NOT NULL DEFAULT FALSE
);
CREATE INDEX misc_data_idx ON misc USING gin (data);

CREATE TABLE notes (
  id integer PRIMARY KEY
);

CREATE TABLE "order" (
  id integer PRIMARY KEY,
  "UserId" integer
);

CREATE TABLE "order items" (
  id integer PRIMARY KEY,
  order_id integer NOT NULL REFERENCES "order" (id) ON DELETE CASCADE,
  "line note" text
);
COMMENT ON COLUMN "order items"."line note" IS 'Quotes '' and " and -- dashes';

CREATE TABLE pairs (
  x integer,
  y integer,
  PRIMARY KEY (x, y)
);

-- Junction table products_categories exists; written as products_categories_2
-- products ↔ keyless (n–n) not written: keyless has no primary key
CREATE TABLE products (
  id integer PRIMARY KEY
);

-- n-n products ↔ categories
CREATE TABLE products_categories_2 (
  products_id integer REFERENCES products (id),
  categories_id integer REFERENCES categories (id),
  PRIMARY KEY (products_id, categories_id)
);

CREATE TABLE products_categories (
  id integer PRIMARY KEY
);

-- stale.mood uses an enum that no longer exists; written as text
-- Index stale_idx on stale names a column that no longer exists; part skipped
-- Relationship stale → a names a column that no longer exists; not written
CREATE TABLE stale (
  id integer PRIMARY KEY,
  mood text
);
CREATE INDEX stale_idx ON stale (id);

-- A table has no name; written as table_9
CREATE TABLE table_9 (
  id integer PRIMARY KEY
);

-- tags ↔ tags (n–n): second side's columns written as tags_id_2
CREATE TABLE tags (
  id integer PRIMARY KEY,
  name varchar(40)
);

-- n-n tags ↔ tags
CREATE TABLE tags_tags (
  tags_id integer REFERENCES tags (id),
  tags_id_2 integer REFERENCES tags (id),
  PRIMARY KEY (tags_id, tags_id_2)
);

-- billing.ledgers.account_id → billing.accounts.id not written: billing.accounts not in this export
CREATE TABLE billing.ledgers (
  id integer PRIMARY KEY,
  account_id uuid
);

CREATE TABLE a (
  id integer PRIMARY KEY,
  b_id integer
);

CREATE TABLE b (
  id integer PRIMARY KEY,
  a_id integer REFERENCES a (id)
);

-- Relationship pair_refs → pairs has 1 and 2 columns; not written
-- Relationship pair_refs → misc names no columns; not a foreign key
CREATE TABLE pair_refs (
  id integer PRIMARY KEY,
  x integer,
  a_id integer REFERENCES a (id)
);

ALTER TABLE a ADD FOREIGN KEY (b_id) REFERENCES b (id);
