-- Edge cases · Edge DB · MySQL
-- Generated by Sododeck. Notes: 16

CREATE DATABASE IF NOT EXISTS billing;

CREATE TABLE categories (
  id int PRIMARY KEY
);

CREATE TABLE keyless (
  v int
);

-- `money` kept as written: not in the common type list for MySQL
-- misc.label: varchar without length written as varchar(255)
-- misc.blank has no type; written as text
-- Enum empty_choice has no values; misc.empty_choice written as text
-- misc.code: auto-increment needs a key in MySQL; dropped
-- Index method gin is not supported by MySQL; misc_data_idx written without it
CREATE TABLE misc (
  id int PRIMARY KEY,
  blank text,
  empty_choice text,
  code text,
  data json,
  price money,
  label varchar(255),
  flag boolean NOT NULL DEFAULT FALSE
);
CREATE INDEX misc_data_idx ON misc (data);

CREATE TABLE notes (
  id int PRIMARY KEY
);

CREATE TABLE `order` (
  id int PRIMARY KEY,
  `UserId` int
);

CREATE TABLE `order items` (
  id int PRIMARY KEY,
  order_id int NOT NULL,
  `line note` text COMMENT 'Quotes '' and " and -- dashes',
  FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE CASCADE
);

CREATE TABLE pairs (
  x int,
  y int,
  PRIMARY KEY (x, y)
);

-- Junction table products_categories exists; written as products_categories_2
-- products ↔ keyless (n–n) not written: keyless has no primary key
CREATE TABLE products (
  id int PRIMARY KEY
);

-- n-n products ↔ categories
CREATE TABLE products_categories_2 (
  products_id int,
  categories_id int,
  PRIMARY KEY (products_id, categories_id),
  FOREIGN KEY (products_id) REFERENCES products (id),
  FOREIGN KEY (categories_id) REFERENCES categories (id)
);

CREATE TABLE products_categories (
  id int PRIMARY KEY
);

-- stale.mood uses an enum that no longer exists; written as text
-- Index stale_idx on stale names a column that no longer exists; part skipped
-- Relationship stale → a names a column that no longer exists; not written
CREATE TABLE stale (
  id int PRIMARY KEY,
  mood text
);
CREATE INDEX stale_idx ON stale (id);

-- A table has no name; written as table_9
CREATE TABLE table_9 (
  id int PRIMARY KEY
);

-- tags ↔ tags (n–n): second side's columns written as tags_id_2
CREATE TABLE tags (
  id int PRIMARY KEY,
  name varchar(40)
);

-- n-n tags ↔ tags
CREATE TABLE tags_tags (
  tags_id int,
  tags_id_2 int,
  PRIMARY KEY (tags_id, tags_id_2),
  FOREIGN KEY (tags_id) REFERENCES tags (id),
  FOREIGN KEY (tags_id_2) REFERENCES tags (id)
);

-- billing.ledgers.account_id → billing.accounts.id not written: billing.accounts not in this export
CREATE TABLE billing.ledgers (
  id int PRIMARY KEY,
  account_id char(36)
);

CREATE TABLE a (
  id int PRIMARY KEY,
  b_id int
);

CREATE TABLE b (
  id int PRIMARY KEY,
  a_id int,
  FOREIGN KEY (a_id) REFERENCES a (id)
);

-- Relationship pair_refs → pairs has 1 and 2 columns; not written
-- Relationship pair_refs → misc names no columns; not a foreign key
CREATE TABLE pair_refs (
  id int PRIMARY KEY,
  x int,
  a_id int,
  FOREIGN KEY (a_id) REFERENCES a (id)
);

ALTER TABLE a ADD FOREIGN KEY (b_id) REFERENCES b (id);
