-- Name clash · Whole deck · Postgres
-- Generated by Sododeck. Notes: 0

CREATE SCHEMA IF NOT EXISTS billing;

CREATE TABLE invoices (
  id integer PRIMARY KEY
);

CREATE TABLE billing.invoices (
  id integer PRIMARY KEY
);
