-- Name clash · Whole deck · MySQL
-- Generated by Sododeck. Notes: 0

CREATE DATABASE IF NOT EXISTS billing;

CREATE TABLE invoices (
  id int PRIMARY KEY
);

CREATE TABLE billing.invoices (
  id int PRIMARY KEY
);
