-- Name clash · Whole deck · SQLite
-- Generated by Sododeck. Notes: 2
-- Schemas are not supported by SQLite: billing.* written without schema

-- Two tables named invoices after dropping schemas
CREATE TABLE invoices (
  id integer PRIMARY KEY
);

CREATE TABLE invoices (
  id integer PRIMARY KEY
);
