-- Shop · Whole deck · SQLite
-- Generated by Sododeck. Notes: 0

CREATE TABLE audit_log (
  id integer NOT NULL,
  "action" text NOT NULL,
  payload text,
  logged_at text NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX audit_log_logged_at_idx ON audit_log (logged_at);

CREATE TABLE categories (
  id text PRIMARY KEY,
  parent_id text REFERENCES categories (id),
  name text NOT NULL
);

-- One row per buyer
CREATE TABLE customers (
  id text PRIMARY KEY,
  email text NOT NULL UNIQUE,
  name text NOT NULL,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX customers_email_lower_idx ON customers (lower(email));

CREATE TABLE addresses (
  id text PRIMARY KEY,
  customer_id text NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
  street text NOT NULL,
  city text NOT NULL,
  -- ISO 3166-1 alpha-2
  country text NOT NULL
);

-- enum order_status: Where an order is in its life
-- order_status.paid: Payment captured
-- One row per checkout
CREATE TABLE orders (
  id text PRIMARY KEY,
  customer_id text NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
  shipping_address_id text REFERENCES addresses (id),
  billing_address_id text REFERENCES addresses (id),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'shipped', 'cancelled')),
  -- Sum of the order items
  total numeric NOT NULL DEFAULT 0,
  created_at text NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX orders_customer_id_idx ON orders (customer_id, created_at);

CREATE TABLE payments (
  id text PRIMARY KEY,
  order_id text NOT NULL REFERENCES orders (id),
  amount numeric NOT NULL,
  paid_at text
);

-- Things we sell; 'active' hides them
-- from the store
CREATE TABLE products (
  id text PRIMARY KEY,
  sku text NOT NULL UNIQUE,
  name text NOT NULL,
  price numeric NOT NULL,
  active integer NOT NULL DEFAULT 1,
  CONSTRAINT products_price_check CHECK (price >= 0)
);

-- n-n products ↔ categories
CREATE TABLE products_categories (
  products_id text REFERENCES products (id),
  categories_id text REFERENCES categories (id),
  PRIMARY KEY (products_id, categories_id)
);

CREATE TABLE order_items (
  order_id text REFERENCES orders (id) ON DELETE CASCADE,
  product_id text REFERENCES products (id) ON DELETE RESTRICT,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL,
  PRIMARY KEY (order_id, product_id)
);

CREATE TABLE reviews (
  id integer PRIMARY KEY AUTOINCREMENT,
  product_id text NOT NULL REFERENCES products (id) ON DELETE CASCADE,
  customer_id text REFERENCES customers (id) ON DELETE SET NULL,
  rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
  body text
);

CREATE TABLE shipments (
  id text PRIMARY KEY,
  order_id text NOT NULL REFERENCES orders (id),
  carrier text,
  shipped_at text
);

CREATE TABLE shipment_items (
  shipment_id text REFERENCES shipments (id) ON DELETE CASCADE,
  order_id text,
  product_id text,
  quantity integer NOT NULL,
  PRIMARY KEY (shipment_id, order_id, product_id),
  FOREIGN KEY (order_id, product_id) REFERENCES order_items (order_id, product_id)
);

CREATE TABLE users (
  id text PRIMARY KEY,
  email text NOT NULL UNIQUE,
  display_name text
);

CREATE TABLE sessions (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token text NOT NULL UNIQUE,
  expires_at text NOT NULL
);
