-- Shop · Whole deck · MySQL
-- Generated by Sododeck. Notes: 0

CREATE TABLE audit_log (
  id bigint NOT NULL,
  `action` varchar(40) NOT NULL,
  payload json,
  logged_at timestamp NOT NULL DEFAULT (now())
);
CREATE INDEX audit_log_logged_at_idx ON audit_log (logged_at) USING BTREE;

CREATE TABLE categories (
  id char(36) PRIMARY KEY,
  parent_id char(36),
  name varchar(100) NOT NULL,
  FOREIGN KEY (parent_id) REFERENCES categories (id)
);

CREATE TABLE customers (
  id char(36) PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  name varchar(120) NOT NULL,
  created_at timestamp NOT NULL DEFAULT (now())
) COMMENT='One row per buyer';
CREATE INDEX customers_email_lower_idx ON customers ((lower(email)));

CREATE TABLE addresses (
  id char(36) PRIMARY KEY,
  customer_id char(36) NOT NULL,
  street varchar(200) NOT NULL,
  city varchar(100) NOT NULL,
  country char(2) NOT NULL COMMENT 'ISO 3166-1 alpha-2',
  FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

-- enum order_status: Where an order is in its life
-- order_status.paid: Payment captured
CREATE TABLE orders (
  id char(36) PRIMARY KEY,
  customer_id char(36) NOT NULL,
  shipping_address_id char(36),
  billing_address_id char(36),
  status enum('pending', 'paid', 'shipped', 'cancelled') NOT NULL DEFAULT 'pending',
  total decimal(10,2) NOT NULL DEFAULT 0 COMMENT 'Sum of the order items',
  created_at timestamp NOT NULL DEFAULT (now()),
  FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
  FOREIGN KEY (shipping_address_id) REFERENCES addresses (id),
  FOREIGN KEY (billing_address_id) REFERENCES addresses (id)
) COMMENT='One row per checkout';
CREATE INDEX orders_customer_id_idx ON orders (customer_id, created_at);

CREATE TABLE payments (
  id char(36) PRIMARY KEY,
  order_id char(36) NOT NULL,
  amount decimal(10,2) NOT NULL,
  paid_at timestamp,
  FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE TABLE products (
  id char(36) PRIMARY KEY,
  sku varchar(40) NOT NULL UNIQUE,
  name varchar(200) NOT NULL,
  price decimal(10,2) NOT NULL,
  active boolean NOT NULL DEFAULT TRUE,
  CONSTRAINT products_price_check CHECK (price >= 0)
) COMMENT='Things we sell; ''active'' hides them
from the store';

-- n-n products ↔ categories
CREATE TABLE products_categories (
  products_id char(36),
  categories_id char(36),
  PRIMARY KEY (products_id, categories_id),
  FOREIGN KEY (products_id) REFERENCES products (id),
  FOREIGN KEY (categories_id) REFERENCES categories (id)
);

CREATE TABLE order_items (
  order_id char(36),
  product_id char(36),
  quantity int NOT NULL CHECK (quantity > 0),
  unit_price decimal(10,2) NOT NULL,
  PRIMARY KEY (order_id, product_id),
  FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT
);

CREATE TABLE reviews (
  id int AUTO_INCREMENT PRIMARY KEY,
  product_id char(36) NOT NULL,
  customer_id char(36),
  rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
  body text,
  FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
  FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL
);

CREATE TABLE shipments (
  id char(36) PRIMARY KEY,
  order_id char(36) NOT NULL,
  carrier varchar(80),
  shipped_at timestamp,
  FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE TABLE shipment_items (
  shipment_id char(36),
  order_id char(36),
  product_id char(36),
  quantity int NOT NULL,
  PRIMARY KEY (shipment_id, order_id, product_id),
  FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON DELETE CASCADE,
  FOREIGN KEY (order_id, product_id) REFERENCES order_items (order_id, product_id)
);

CREATE TABLE users (
  id char(36) PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  display_name varchar(80)
);

CREATE TABLE sessions (
  id char(36) PRIMARY KEY,
  user_id char(36) NOT NULL,
  token varchar(64) NOT NULL UNIQUE,
  expires_at timestamp NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
