-- Shop · Whole deck · Postgres
-- Generated by Sododeck. Notes: 0

CREATE TABLE audit_log (
  id bigint NOT NULL,
  "action" varchar(40) NOT NULL,
  payload jsonb,
  logged_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_logged_at_idx ON audit_log USING btree (logged_at);

CREATE TABLE categories (
  id uuid PRIMARY KEY,
  parent_id uuid REFERENCES categories (id),
  name varchar(100) NOT NULL
);

CREATE TABLE customers (
  id uuid PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  name varchar(120) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE customers IS 'One row per buyer';
CREATE INDEX customers_email_lower_idx ON customers ((lower(email)));

CREATE TABLE addresses (
  id uuid PRIMARY KEY,
  customer_id uuid NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
  street varchar(200) NOT NULL,
  city varchar(100) NOT NULL,
  country char(2) NOT NULL
);
COMMENT ON COLUMN addresses.country IS 'ISO 3166-1 alpha-2';

-- order_status.paid: Payment captured
CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped', 'cancelled');
COMMENT ON TYPE order_status IS 'Where an order is in its life';

CREATE TABLE orders (
  id uuid PRIMARY KEY,
  customer_id uuid NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
  shipping_address_id uuid REFERENCES addresses (id),
  billing_address_id uuid REFERENCES addresses (id),
  status order_status NOT NULL DEFAULT 'pending',
  total numeric(10,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE orders IS 'One row per checkout';
COMMENT ON COLUMN orders.total IS 'Sum of the order items';
CREATE INDEX orders_customer_id_idx ON orders (customer_id, created_at);

CREATE TABLE payments (
  id uuid PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES orders (id),
  amount numeric(10,2) NOT NULL,
  paid_at timestamptz
);

CREATE TABLE products (
  id uuid PRIMARY KEY,
  sku varchar(40) NOT NULL UNIQUE,
  name varchar(200) NOT NULL,
  price numeric(10,2) NOT NULL,
  active boolean NOT NULL DEFAULT TRUE,
  CONSTRAINT products_price_check CHECK (price >= 0)
);
COMMENT ON TABLE products IS 'Things we sell; ''active'' hides them
from the store';

-- n-n products ↔ categories
CREATE TABLE products_categories (
  products_id uuid REFERENCES products (id),
  categories_id uuid REFERENCES categories (id),
  PRIMARY KEY (products_id, categories_id)
);

CREATE TABLE order_items (
  order_id uuid REFERENCES orders (id) ON DELETE CASCADE,
  product_id uuid REFERENCES products (id) ON DELETE RESTRICT,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric(10,2) NOT NULL,
  PRIMARY KEY (order_id, product_id)
);

CREATE TABLE reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id uuid NOT NULL REFERENCES products (id) ON DELETE CASCADE,
  customer_id uuid REFERENCES customers (id) ON DELETE SET NULL,
  rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
  body text
);

CREATE TABLE shipments (
  id uuid PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES orders (id),
  carrier varchar(80),
  shipped_at timestamptz
);

CREATE TABLE shipment_items (
  shipment_id uuid REFERENCES shipments (id) ON DELETE CASCADE,
  order_id uuid,
  product_id uuid,
  quantity integer NOT NULL,
  PRIMARY KEY (shipment_id, order_id, product_id),
  FOREIGN KEY (order_id, product_id) REFERENCES order_items (order_id, product_id)
);

CREATE TABLE users (
  id uuid PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  display_name varchar(80)
);

CREATE TABLE sessions (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token varchar(64) NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL
);
