/**
 * Generates TypeScript types and Zod validators from schema/v1.json.
 *
 *   pnpm generate          write src/generated/*
 *   pnpm generate --check  fail if src/generated/* is out of date (used in tests/CI)
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import { compile, type JSONSchema } from 'json-schema-to-typescript';
import { jsonSchemaToZod } from 'json-schema-to-zod';
import { format } from 'prettier';

const root = fileURLToPath(new URL('..', import.meta.url));
const schemaPath = `${root}schema/v1.json`;
const banner = '// GENERATED by scripts/generate.ts from schema/v1.json. Do not edit.\n';

// Both generators mishandle `anyOf` presence rules (e.g. "a sticky needs an anchor or a
// position"): json-schema-to-zod turns them into `z.any()` and json-schema-to-typescript into an
// index signature. They stay in v1.json for Ajv/Monaco; `checkSemanticRules` enforces them for Zod.
const schema = stripPresenceRules(
  JSON.parse(await readFile(schemaPath, 'utf8')) as unknown,
) as JSONSchema;

// json-schema-to-typescript turns every `$ref` with a sibling (our per-field `description`) into
// a new alias (`Id1`, `Text2`, …). Types only need the ref; descriptions stay in v1.json.
const types = await compile(bareRefs(schema) as JSONSchema, 'SododeckFile', {
  bannerComment: '',
  additionalProperties: false,
  unreachableDefinitions: true,
  // minItems would emit a non-empty tuple type that the Zod output (string[]) is not assignable to.
  ignoreMinAndMaxItems: true,
});

// json-schema-to-zod does not follow $ref, so inline local refs first.
const zod = jsonSchemaToZod(dereference(schema, schema) as JSONSchema, {
  name: 'sododeckFileSchema',
  module: 'esm',
  type: true,
});

const outputs: Record<string, string> = {
  [`${root}src/generated/types.ts`]: banner + types,
  [`${root}src/generated/zod.ts`]: banner + zod,
};

const check = process.argv.includes('--check');
let stale = false;

for (const [file, raw] of Object.entries(outputs)) {
  const content = await format(raw, { parser: 'typescript', singleQuote: true, printWidth: 100 });
  if (check) {
    const current = await readFile(file, 'utf8').catch(() => '');
    if (current !== content) {
      console.error(`Out of date: ${file}`);
      stale = true;
    }
  } else {
    await writeFile(file, content);
    console.log(`Wrote ${file}`);
  }
}

if (stale) {
  console.error('Run `pnpm schema:generate` and commit the result.');
  process.exit(1);
}

/** Inlines local `#/$defs/...` refs. Throws on cycles (not supported by the Zod generator). */
function dereference(node: unknown, rootSchema: JSONSchema, seen: string[] = []): unknown {
  if (Array.isArray(node)) return node.map((item) => dereference(item, rootSchema, seen));
  if (node === null || typeof node !== 'object') return node;

  const { $ref, ...rest } = node as Record<string, unknown>;
  if (typeof $ref === 'string') {
    if (!$ref.startsWith('#/$defs/')) throw new Error(`Unsupported $ref: ${$ref}`);
    if (seen.includes($ref)) throw new Error(`Recursive $ref not supported: ${$ref}`);
    const defs = (rootSchema as { $defs?: Record<string, unknown> }).$defs ?? {};
    const target = defs[$ref.slice('#/$defs/'.length)];
    if (target === undefined) throw new Error(`Unresolved $ref: ${$ref}`);
    return { ...(dereference(target, rootSchema, [...seen, $ref]) as object), ...rest };
  }

  return Object.fromEntries(
    Object.entries(rest)
      .filter(([key]) => key !== '$defs')
      .map(([key, value]) => [key, dereference(value, rootSchema, seen)]),
  );
}

/** Removes `anyOf` whose branches only require that some property is present. */
function stripPresenceRules(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(stripPresenceRules);
  if (node === null || typeof node !== 'object') return node;

  const { anyOf, ...rest } = node as Record<string, unknown>;
  const stripped = Object.fromEntries(
    Object.entries(rest).map(([key, value]) => [key, stripPresenceRules(value)]),
  );
  if (anyOf === undefined) return stripped;
  if (Array.isArray(anyOf) && anyOf.every(isPresenceRule)) return stripped;
  return { ...stripped, anyOf: stripPresenceRules(anyOf) };
}

function isPresenceRule(branch: unknown): boolean {
  if (branch === null || typeof branch !== 'object') return false;
  const { properties, required, ...other } = branch as Record<string, unknown>;
  return (
    Object.keys(other).length === 0 &&
    Array.isArray(required) &&
    (properties === undefined ||
      (typeof properties === 'object' &&
        properties !== null &&
        Object.values(properties).every((value) => value === true)))
  );
}

/** Drops keys next to `$ref` (e.g. `description`), so refs resolve to the named definition. */
function bareRefs(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(bareRefs);
  if (node === null || typeof node !== 'object') return node;
  const record = node as Record<string, unknown>;
  if (typeof record.$ref === 'string') return { $ref: record.$ref };
  return Object.fromEntries(Object.entries(record).map(([key, value]) => [key, bareRefs(value)]));
}
