// Hand-written data: the curated Lucide icon list for the built-in icon set.
// Adding an icon = one entry here + `pnpm icons:generate`.
import type { IconCategory } from './types';

export interface CatalogEntry {
  name: string;
  label: string;
  category: string;
  keywords: readonly string[];
}

export const LUCIDE_CATEGORIES: readonly IconCategory[] = [
  { id: 'compute', label: 'Compute' },
  { id: 'data', label: 'Data' },
  { id: 'network', label: 'Network' },
  { id: 'cloud', label: 'Cloud' },
  { id: 'security', label: 'Security' },
  { id: 'people', label: 'People' },
  { id: 'devices', label: 'Devices' },
  { id: 'messaging', label: 'Messaging' },
  { id: 'files', label: 'Files' },
  { id: 'business', label: 'Business' },
  { id: 'logistics', label: 'Logistics' },
  { id: 'status-shapes', label: 'Status & Shapes' },
];

export const LUCIDE_CATALOG: readonly CatalogEntry[] = [
  { name: 'cpu', label: 'CPU', category: 'compute', keywords: ['processor', 'chip', 'compute'] },
  { name: 'memory-stick', label: 'Memory', category: 'compute', keywords: ['ram', 'dimm', 'chip'] },
  {
    name: 'microchip',
    label: 'Microchip',
    category: 'compute',
    keywords: ['chip', 'silicon', 'hardware'],
  },
  {
    name: 'container',
    label: 'Container',
    category: 'compute',
    keywords: ['docker', 'pod', 'package'],
  },
  { name: 'box', label: 'Box', category: 'compute', keywords: ['cube', 'package', 'component'] },
  { name: 'boxes', label: 'Boxes', category: 'compute', keywords: ['cluster', 'group', 'modules'] },
  { name: 'code', label: 'Code', category: 'compute', keywords: ['source', 'program', 'dev'] },
  {
    name: 'code-xml',
    label: 'Code XML',
    category: 'compute',
    keywords: ['markup', 'html', 'source'],
  },
  {
    name: 'terminal',
    label: 'Terminal',
    category: 'compute',
    keywords: ['shell', 'console', 'cli'],
  },
  {
    name: 'square-terminal',
    label: 'Terminal window',
    category: 'compute',
    keywords: ['shell', 'console', 'cli'],
  },
  { name: 'braces', label: 'Braces', category: 'compute', keywords: ['json', 'object', 'code'] },
  { name: 'brackets', label: 'Brackets', category: 'compute', keywords: ['array', 'list', 'code'] },
  {
    name: 'square-function',
    label: 'Function',
    category: 'compute',
    keywords: ['lambda', 'serverless', 'fn'],
  },
  {
    name: 'variable',
    label: 'Variable',
    category: 'compute',
    keywords: ['param', 'symbol', 'value'],
  },
  {
    name: 'regex',
    label: 'Regex',
    category: 'compute',
    keywords: ['pattern', 'match', 'expression'],
  },
  { name: 'bug', label: 'Bug', category: 'compute', keywords: ['defect', 'issue', 'error'] },
  { name: 'bug-play', label: 'Debug', category: 'compute', keywords: ['run', 'test', 'issue'] },
  {
    name: 'git-branch',
    label: 'Branch',
    category: 'compute',
    keywords: ['git', 'fork', 'version'],
  },
  {
    name: 'git-commit-horizontal',
    label: 'Commit',
    category: 'compute',
    keywords: ['git', 'change', 'version'],
  },
  { name: 'git-merge', label: 'Merge', category: 'compute', keywords: ['git', 'join', 'combine'] },
  {
    name: 'git-pull-request',
    label: 'Pull request',
    category: 'compute',
    keywords: ['git', 'review', 'merge'],
  },
  { name: 'git-fork', label: 'Fork', category: 'compute', keywords: ['git', 'split', 'copy'] },
  {
    name: 'workflow',
    label: 'Workflow',
    category: 'compute',
    keywords: ['pipeline', 'process', 'automation'],
  },
  {
    name: 'blocks',
    label: 'Blocks',
    category: 'compute',
    keywords: ['modules', 'components', 'build'],
  },
  {
    name: 'component',
    label: 'Component',
    category: 'compute',
    keywords: ['module', 'part', 'widget'],
  },
  {
    name: 'puzzle',
    label: 'Puzzle',
    category: 'compute',
    keywords: ['plugin', 'extension', 'integration'],
  },
  {
    name: 'plug',
    label: 'Plug',
    category: 'compute',
    keywords: ['connector', 'plugin', 'adapter'],
  },
  {
    name: 'database',
    label: 'Database',
    category: 'data',
    keywords: ['db', 'sql', 'storage', 'table'],
  },
  {
    name: 'database-zap',
    label: 'Fast database',
    category: 'data',
    keywords: ['cache', 'db', 'speed'],
  },
  {
    name: 'database-backup',
    label: 'Database backup',
    category: 'data',
    keywords: ['db', 'snapshot', 'restore'],
  },
  {
    name: 'hard-drive',
    label: 'Hard drive',
    category: 'data',
    keywords: ['disk', 'db', 'storage'],
  },
  {
    name: 'hard-drive-download',
    label: 'Disk download',
    category: 'data',
    keywords: ['disk', 'import', 'restore'],
  },
  {
    name: 'hard-drive-upload',
    label: 'Disk upload',
    category: 'data',
    keywords: ['disk', 'export', 'backup'],
  },
  { name: 'table', label: 'Table', category: 'data', keywords: ['grid', 'rows', 'sql'] },
  {
    name: 'table-2',
    label: 'Table grid',
    category: 'data',
    keywords: ['grid', 'rows', 'spreadsheet'],
  },
  { name: 'sheet', label: 'Spreadsheet', category: 'data', keywords: ['sheet', 'grid', 'excel'] },
  {
    name: 'columns-3',
    label: 'Columns',
    category: 'data',
    keywords: ['fields', 'layout', 'table'],
  },
  { name: 'rows-3', label: 'Rows', category: 'data', keywords: ['records', 'layout', 'table'] },
  { name: 'layers', label: 'Layers', category: 'data', keywords: ['stack', 'tiers', 'levels'] },
  {
    name: 'layers-2',
    label: 'Two layers',
    category: 'data',
    keywords: ['stack', 'tiers', 'levels'],
  },
  { name: 'list', label: 'List', category: 'data', keywords: ['items', 'rows', 'bullets'] },
  {
    name: 'list-tree',
    label: 'Tree list',
    category: 'data',
    keywords: ['hierarchy', 'outline', 'nested'],
  },
  {
    name: 'list-ordered',
    label: 'Ordered list',
    category: 'data',
    keywords: ['sequence', 'numbered', 'steps'],
  },
  {
    name: 'list-checks',
    label: 'Checklist',
    category: 'data',
    keywords: ['tasks', 'todo', 'done'],
  },
  {
    name: 'list-filter',
    label: 'Filtered list',
    category: 'data',
    keywords: ['filter', 'query', 'narrow'],
  },
  { name: 'funnel', label: 'Filter', category: 'data', keywords: ['funnel', 'narrow', 'query'] },
  {
    name: 'arrow-down-wide-narrow',
    label: 'Sort',
    category: 'data',
    keywords: ['order', 'rank', 'descending'],
  },
  {
    name: 'arrow-up-down',
    label: 'Sort vertical',
    category: 'data',
    keywords: ['swap', 'order', 'transfer'],
  },
  {
    name: 'arrow-left-right',
    label: 'Exchange',
    category: 'data',
    keywords: ['swap', 'transfer', 'sync'],
  },
  { name: 'repeat', label: 'Repeat', category: 'data', keywords: ['loop', 'cycle', 'again'] },
  {
    name: 'repeat-2',
    label: 'Repeat once',
    category: 'data',
    keywords: ['loop', 'cycle', 'retry'],
  },
  {
    name: 'network',
    label: 'Network',
    category: 'network',
    keywords: ['topology', 'graph', 'nodes'],
  },
  { name: 'globe', label: 'Globe', category: 'network', keywords: ['web', 'internet', 'world'] },
  {
    name: 'globe-lock',
    label: 'Secure web',
    category: 'network',
    keywords: ['https', 'tls', 'internet'],
  },
  { name: 'earth', label: 'Earth', category: 'network', keywords: ['world', 'global', 'planet'] },
  {
    name: 'router',
    label: 'Router',
    category: 'network',
    keywords: ['gateway', 'network', 'switch'],
  },
  {
    name: 'server',
    label: 'Server',
    category: 'network',
    keywords: ['host', 'machine', 'node', 'db'],
  },
  {
    name: 'server-cog',
    label: 'Managed server',
    category: 'network',
    keywords: ['host', 'config', 'node'],
  },
  {
    name: 'server-crash',
    label: 'Server error',
    category: 'network',
    keywords: ['host', 'down', 'failure'],
  },
  {
    name: 'server-off',
    label: 'Server off',
    category: 'network',
    keywords: ['host', 'down', 'offline'],
  },
  {
    name: 'wifi',
    label: 'Wi-Fi',
    category: 'network',
    keywords: ['wireless', 'network', 'signal'],
  },
  {
    name: 'wifi-off',
    label: 'Wi-Fi off',
    category: 'network',
    keywords: ['offline', 'disconnected', 'no signal'],
  },
  {
    name: 'signal',
    label: 'Signal',
    category: 'network',
    keywords: ['strength', 'wireless', 'bars'],
  },
  {
    name: 'radio',
    label: 'Radio',
    category: 'network',
    keywords: ['broadcast', 'signal', 'wireless'],
  },
  {
    name: 'radio-tower',
    label: 'Radio tower',
    category: 'network',
    keywords: ['antenna', 'broadcast', 'transmit'],
  },
  {
    name: 'antenna',
    label: 'Antenna',
    category: 'network',
    keywords: ['signal', 'receive', 'wireless'],
  },
  {
    name: 'satellite',
    label: 'Satellite',
    category: 'network',
    keywords: ['orbit', 'space', 'uplink'],
  },
  {
    name: 'satellite-dish',
    label: 'Satellite dish',
    category: 'network',
    keywords: ['receiver', 'signal', 'uplink'],
  },
  { name: 'cable', label: 'Cable', category: 'network', keywords: ['wire', 'link', 'connection'] },
  {
    name: 'ethernet-port',
    label: 'Ethernet port',
    category: 'network',
    keywords: ['lan', 'socket', 'network'],
  },
  { name: 'usb', label: 'USB', category: 'network', keywords: ['port', 'connector', 'device'] },
  {
    name: 'bluetooth',
    label: 'Bluetooth',
    category: 'network',
    keywords: ['wireless', 'pairing', 'short range'],
  },
  { name: 'link', label: 'Link', category: 'network', keywords: ['url', 'connection', 'chain'] },
  {
    name: 'link-2',
    label: 'Short link',
    category: 'network',
    keywords: ['url', 'connection', 'chain'],
  },
  {
    name: 'unlink',
    label: 'Unlink',
    category: 'network',
    keywords: ['disconnect', 'break', 'detach'],
  },
  {
    name: 'external-link',
    label: 'External link',
    category: 'network',
    keywords: ['open', 'url', 'out'],
  },
  { name: 'route', label: 'Route', category: 'network', keywords: ['path', 'journey', 'hops'] },
  { name: 'cloud', label: 'Cloud', category: 'cloud', keywords: ['saas', 'hosting', 'remote'] },
  {
    name: 'cloud-cog',
    label: 'Cloud config',
    category: 'cloud',
    keywords: ['settings', 'managed', 'saas'],
  },
  {
    name: 'cloud-lightning',
    label: 'Cloud function',
    category: 'cloud',
    keywords: ['serverless', 'storm', 'event'],
  },
  {
    name: 'cloud-off',
    label: 'Cloud offline',
    category: 'cloud',
    keywords: ['disconnected', 'down', 'no sync'],
  },
  {
    name: 'cloud-check',
    label: 'Cloud synced',
    category: 'cloud',
    keywords: ['done', 'saved', 'ok'],
  },
  {
    name: 'cloud-alert',
    label: 'Cloud alert',
    category: 'cloud',
    keywords: ['warning', 'issue', 'incident'],
  },
  {
    name: 'cloud-sun',
    label: 'Cloud and sun',
    category: 'cloud',
    keywords: ['weather', 'partly', 'forecast'],
  },
  {
    name: 'cloud-rain',
    label: 'Rain',
    category: 'cloud',
    keywords: ['weather', 'wet', 'forecast'],
  },
  {
    name: 'cloud-snow',
    label: 'Snow',
    category: 'cloud',
    keywords: ['weather', 'cold', 'forecast'],
  },
  {
    name: 'cloud-fog',
    label: 'Fog',
    category: 'cloud',
    keywords: ['weather', 'mist', 'low visibility'],
  },
  {
    name: 'cloud-drizzle',
    label: 'Drizzle',
    category: 'cloud',
    keywords: ['weather', 'light rain', 'forecast'],
  },
  {
    name: 'cloud-hail',
    label: 'Hail',
    category: 'cloud',
    keywords: ['weather', 'storm', 'forecast'],
  },
  {
    name: 'cloud-moon',
    label: 'Cloud and moon',
    category: 'cloud',
    keywords: ['night', 'weather', 'partly'],
  },
  { name: 'sun', label: 'Sun', category: 'cloud', keywords: ['day', 'light', 'weather'] },
  { name: 'moon', label: 'Moon', category: 'cloud', keywords: ['night', 'dark', 'theme'] },
  {
    name: 'snowflake',
    label: 'Snowflake',
    category: 'cloud',
    keywords: ['cold', 'freeze', 'winter'],
  },
  {
    name: 'thermometer',
    label: 'Thermometer',
    category: 'cloud',
    keywords: ['temperature', 'heat', 'sensor'],
  },
  {
    name: 'thermometer-sun',
    label: 'Hot',
    category: 'cloud',
    keywords: ['temperature', 'heat', 'warm'],
  },
  {
    name: 'thermometer-snowflake',
    label: 'Cold',
    category: 'cloud',
    keywords: ['temperature', 'freeze', 'chill'],
  },
  { name: 'droplet', label: 'Droplet', category: 'cloud', keywords: ['water', 'liquid', 'drop'] },
  { name: 'droplets', label: 'Droplets', category: 'cloud', keywords: ['water', 'rain', 'liquid'] },
  {
    name: 'waves-horizontal',
    label: 'Waves',
    category: 'cloud',
    keywords: ['water', 'sea', 'stream'],
  },
  { name: 'zap', label: 'Zap', category: 'cloud', keywords: ['lightning', 'power', 'fast'] },
  { name: 'lock', label: 'Lock', category: 'security', keywords: ['secure', 'private', 'closed'] },
  {
    name: 'lock-open',
    label: 'Unlock',
    category: 'security',
    keywords: ['open', 'access', 'unsecured'],
  },
  {
    name: 'lock-keyhole',
    label: 'Keyhole lock',
    category: 'security',
    keywords: ['secure', 'private', 'vault'],
  },
  {
    name: 'key-round',
    label: 'Key',
    category: 'security',
    keywords: ['credential', 'secret', 'access'],
  },
  {
    name: 'key',
    label: 'Plain key',
    category: 'security',
    keywords: ['credential', 'secret', 'access'],
  },
  {
    name: 'shield',
    label: 'Shield',
    category: 'security',
    keywords: ['security', 'protect', 'guard'],
  },
  {
    name: 'shield-check',
    label: 'Verified shield',
    category: 'security',
    keywords: ['secure', 'approved', 'trusted'],
  },
  {
    name: 'shield-alert',
    label: 'Shield alert',
    category: 'security',
    keywords: ['threat', 'warning', 'risk'],
  },
  {
    name: 'shield-ban',
    label: 'Shield block',
    category: 'security',
    keywords: ['deny', 'blocked', 'firewall'],
  },
  {
    name: 'shield-half',
    label: 'Shield half',
    category: 'security',
    keywords: ['protection', 'partial', 'defense'],
  },
  {
    name: 'shield-off',
    label: 'Shield off',
    category: 'security',
    keywords: ['unprotected', 'disabled', 'risk'],
  },
  {
    name: 'shield-user',
    label: 'User shield',
    category: 'security',
    keywords: ['identity', 'protected', 'account'],
  },
  {
    name: 'shield-plus',
    label: 'Shield plus',
    category: 'security',
    keywords: ['add', 'protect', 'security'],
  },
  {
    name: 'shield-question-mark',
    label: 'Shield unknown',
    category: 'security',
    keywords: ['unverified', 'query', 'risk'],
  },
  {
    name: 'fingerprint-pattern',
    label: 'Fingerprint',
    category: 'security',
    keywords: ['biometric', 'identity', 'auth'],
  },
  {
    name: 'scan-face',
    label: 'Face scan',
    category: 'security',
    keywords: ['biometric', 'identity', 'auth'],
  },
  {
    name: 'scan-eye',
    label: 'Eye scan',
    category: 'security',
    keywords: ['biometric', 'retina', 'auth'],
  },
  { name: 'eye', label: 'Eye', category: 'security', keywords: ['view', 'visible', 'watch'] },
  {
    name: 'eye-off',
    label: 'Hidden',
    category: 'security',
    keywords: ['invisible', 'private', 'mask'],
  },
  { name: 'vault', label: 'Vault', category: 'security', keywords: ['safe', 'secure', 'storage'] },
  {
    name: 'shield-ellipsis',
    label: 'Shield pending',
    category: 'security',
    keywords: ['checking', 'scan', 'progress'],
  },
  {
    name: 'file-lock',
    label: 'Locked file',
    category: 'security',
    keywords: ['encrypted', 'protected', 'document'],
  },
  {
    name: 'folder-lock',
    label: 'Locked folder',
    category: 'security',
    keywords: ['encrypted', 'protected', 'directory'],
  },
  {
    name: 'user-lock',
    label: 'Locked user',
    category: 'security',
    keywords: ['account', 'restricted', 'protected'],
  },
  { name: 'user', label: 'User', category: 'people', keywords: ['person', 'account', 'profile'] },
  {
    name: 'user-round',
    label: 'Person',
    category: 'people',
    keywords: ['user', 'account', 'profile'],
  },
  { name: 'users', label: 'Users', category: 'people', keywords: ['people', 'team', 'group'] },
  {
    name: 'users-round',
    label: 'Team',
    category: 'people',
    keywords: ['people', 'group', 'staff'],
  },
  {
    name: 'user-plus',
    label: 'Add user',
    category: 'people',
    keywords: ['invite', 'new', 'account'],
  },
  {
    name: 'user-minus',
    label: 'Remove user',
    category: 'people',
    keywords: ['delete', 'leave', 'account'],
  },
  {
    name: 'user-check',
    label: 'Verified user',
    category: 'people',
    keywords: ['approved', 'active', 'account'],
  },
  {
    name: 'user-x',
    label: 'Blocked user',
    category: 'people',
    keywords: ['banned', 'removed', 'account'],
  },
  {
    name: 'user-cog',
    label: 'User settings',
    category: 'people',
    keywords: ['account', 'admin', 'config'],
  },
  {
    name: 'user-pen',
    label: 'Edit user',
    category: 'people',
    keywords: ['profile', 'account', 'modify'],
  },
  {
    name: 'user-search',
    label: 'Find user',
    category: 'people',
    keywords: ['lookup', 'search', 'directory'],
  },
  {
    name: 'user-star',
    label: 'Key user',
    category: 'people',
    keywords: ['vip', 'favorite', 'owner'],
  },
  {
    name: 'contact',
    label: 'Contact',
    category: 'people',
    keywords: ['address book', 'person', 'card'],
  },
  {
    name: 'contact-round',
    label: 'Contact card',
    category: 'people',
    keywords: ['address book', 'person', 'directory'],
  },
  {
    name: 'circle-user',
    label: 'User avatar',
    category: 'people',
    keywords: ['account', 'profile', 'person'],
  },
  {
    name: 'circle-user-round',
    label: 'Avatar',
    category: 'people',
    keywords: ['account', 'profile', 'person'],
  },
  {
    name: 'square-user',
    label: 'User tile',
    category: 'people',
    keywords: ['account', 'profile', 'person'],
  },
  { name: 'baby', label: 'Baby', category: 'people', keywords: ['child', 'infant', 'small'] },
  {
    name: 'person-standing',
    label: 'Standing person',
    category: 'people',
    keywords: ['human', 'figure', 'accessibility'],
  },
  {
    name: 'accessibility',
    label: 'Accessibility',
    category: 'people',
    keywords: ['a11y', 'inclusive', 'access'],
  },
  { name: 'hand', label: 'Hand', category: 'people', keywords: ['stop', 'wave', 'manual'] },
  {
    name: 'hand-helping',
    label: 'Support',
    category: 'people',
    keywords: ['help', 'assist', 'aid'],
  },
  {
    name: 'handshake',
    label: 'Handshake',
    category: 'people',
    keywords: ['deal', 'partner', 'agreement'],
  },
  {
    name: 'monitor',
    label: 'Monitor',
    category: 'devices',
    keywords: ['screen', 'display', 'desktop'],
  },
  {
    name: 'monitor-smartphone',
    label: 'Multi-device',
    category: 'devices',
    keywords: ['responsive', 'cross platform', 'screens'],
  },
  {
    name: 'monitor-check',
    label: 'Monitor ok',
    category: 'devices',
    keywords: ['screen', 'healthy', 'done'],
  },
  {
    name: 'monitor-cog',
    label: 'Monitor settings',
    category: 'devices',
    keywords: ['screen', 'config', 'display'],
  },
  {
    name: 'monitor-play',
    label: 'Monitor play',
    category: 'devices',
    keywords: ['screen', 'video', 'present'],
  },
  {
    name: 'monitor-up',
    label: 'Monitor upload',
    category: 'devices',
    keywords: ['screen', 'publish', 'send'],
  },
  {
    name: 'monitor-x',
    label: 'Monitor error',
    category: 'devices',
    keywords: ['screen', 'closed', 'fail'],
  },
  {
    name: 'laptop',
    label: 'Laptop',
    category: 'devices',
    keywords: ['notebook', 'computer', 'pc'],
  },
  {
    name: 'laptop-minimal',
    label: 'Laptop minimal',
    category: 'devices',
    keywords: ['notebook', 'computer', 'pc'],
  },
  {
    name: 'smartphone',
    label: 'Smartphone',
    category: 'devices',
    keywords: ['phone', 'mobile', 'cell'],
  },
  {
    name: 'smartphone-nfc',
    label: 'Contactless phone',
    category: 'devices',
    keywords: ['nfc', 'tap', 'mobile'],
  },
  { name: 'tablet', label: 'Tablet', category: 'devices', keywords: ['ipad', 'mobile', 'screen'] },
  {
    name: 'tablet-smartphone',
    label: 'Phone and tablet',
    category: 'devices',
    keywords: ['mobile', 'responsive', 'device'],
  },
  { name: 'tv', label: 'TV', category: 'devices', keywords: ['television', 'screen', 'display'] },
  {
    name: 'tv-minimal',
    label: 'TV minimal',
    category: 'devices',
    keywords: ['television', 'screen', 'display'],
  },
  {
    name: 'watch',
    label: 'Watch',
    category: 'devices',
    keywords: ['wearable', 'time', 'smartwatch'],
  },
  {
    name: 'keyboard',
    label: 'Keyboard',
    category: 'devices',
    keywords: ['input', 'keys', 'typing'],
  },
  { name: 'mouse', label: 'Mouse', category: 'devices', keywords: ['pointer', 'input', 'click'] },
  {
    name: 'mouse-pointer',
    label: 'Pointer',
    category: 'devices',
    keywords: ['cursor', 'click', 'select'],
  },
  {
    name: 'mouse-pointer-click',
    label: 'Click',
    category: 'devices',
    keywords: ['tap', 'press', 'select'],
  },
  {
    name: 'printer',
    label: 'Printer',
    category: 'devices',
    keywords: ['print', 'output', 'paper'],
  },
  {
    name: 'printer-check',
    label: 'Printer ready',
    category: 'devices',
    keywords: ['print', 'done', 'paper'],
  },
  { name: 'mail', label: 'Mail', category: 'messaging', keywords: ['email', 'message', 'inbox'] },
  {
    name: 'mail-open',
    label: 'Opened mail',
    category: 'messaging',
    keywords: ['email', 'read', 'message'],
  },
  {
    name: 'mail-check',
    label: 'Mail delivered',
    category: 'messaging',
    keywords: ['email', 'sent', 'ok'],
  },
  {
    name: 'mail-plus',
    label: 'New mail',
    category: 'messaging',
    keywords: ['email', 'compose', 'add'],
  },
  {
    name: 'mail-warning',
    label: 'Mail warning',
    category: 'messaging',
    keywords: ['email', 'spam', 'alert'],
  },
  {
    name: 'mails',
    label: 'Mailing list',
    category: 'messaging',
    keywords: ['email', 'bulk', 'newsletter'],
  },
  {
    name: 'inbox',
    label: 'Inbox',
    category: 'messaging',
    keywords: ['incoming', 'queue', 'messages'],
  },
  {
    name: 'send',
    label: 'Send',
    category: 'messaging',
    keywords: ['submit', 'deliver', 'message'],
  },
  {
    name: 'send-horizontal',
    label: 'Send message',
    category: 'messaging',
    keywords: ['submit', 'deliver', 'reply'],
  },
  { name: 'reply', label: 'Reply', category: 'messaging', keywords: ['respond', 'answer', 'back'] },
  {
    name: 'reply-all',
    label: 'Reply all',
    category: 'messaging',
    keywords: ['respond', 'everyone', 'answer'],
  },
  {
    name: 'message-square',
    label: 'Chat',
    category: 'messaging',
    keywords: ['message', 'comment', 'talk'],
  },
  {
    name: 'message-square-text',
    label: 'Chat text',
    category: 'messaging',
    keywords: ['message', 'comment', 'note'],
  },
  {
    name: 'message-square-more',
    label: 'Chat pending',
    category: 'messaging',
    keywords: ['message', 'typing', 'wait'],
  },
  {
    name: 'message-square-warning',
    label: 'Chat warning',
    category: 'messaging',
    keywords: ['message', 'alert', 'issue'],
  },
  {
    name: 'message-square-dashed',
    label: 'Draft message',
    category: 'messaging',
    keywords: ['message', 'pending', 'placeholder'],
  },
  {
    name: 'message-circle',
    label: 'Chat bubble',
    category: 'messaging',
    keywords: ['message', 'comment', 'talk'],
  },
  {
    name: 'messages-square',
    label: 'Conversation',
    category: 'messaging',
    keywords: ['messages', 'thread', 'chat'],
  },
  {
    name: 'megaphone',
    label: 'Announcement',
    category: 'messaging',
    keywords: ['broadcast', 'promote', 'notify'],
  },
  {
    name: 'bell',
    label: 'Bell',
    category: 'messaging',
    keywords: ['notification', 'alert', 'reminder'],
  },
  {
    name: 'bell-ring',
    label: 'Bell ringing',
    category: 'messaging',
    keywords: ['notification', 'alert', 'alarm'],
  },
  {
    name: 'bell-off',
    label: 'Bell muted',
    category: 'messaging',
    keywords: ['notification', 'silent', 'off'],
  },
  {
    name: 'bell-plus',
    label: 'New alert',
    category: 'messaging',
    keywords: ['notification', 'subscribe', 'add'],
  },
  {
    name: 'at-sign',
    label: 'At sign',
    category: 'messaging',
    keywords: ['mention', 'email', 'handle'],
  },
  { name: 'file', label: 'File', category: 'files', keywords: ['document', 'page', 'blank'] },
  { name: 'file-text', label: 'Document', category: 'files', keywords: ['file', 'text', 'page'] },
  { name: 'files', label: 'Files', category: 'files', keywords: ['documents', 'copies', 'pages'] },
  {
    name: 'file-plus',
    label: 'New file',
    category: 'files',
    keywords: ['add', 'create', 'document'],
  },
  {
    name: 'file-minus',
    label: 'Remove file',
    category: 'files',
    keywords: ['delete', 'document', 'minus'],
  },
  {
    name: 'file-check',
    label: 'Approved file',
    category: 'files',
    keywords: ['done', 'verified', 'document'],
  },
  {
    name: 'file-x',
    label: 'Rejected file',
    category: 'files',
    keywords: ['error', 'invalid', 'document'],
  },
  {
    name: 'file-search',
    label: 'Search file',
    category: 'files',
    keywords: ['find', 'lookup', 'document'],
  },
  {
    name: 'file-clock',
    label: 'File history',
    category: 'files',
    keywords: ['version', 'time', 'document'],
  },
  {
    name: 'file-input',
    label: 'File in',
    category: 'files',
    keywords: ['import', 'receive', 'document'],
  },
  {
    name: 'file-output',
    label: 'File out',
    category: 'files',
    keywords: ['export', 'send', 'document'],
  },
  {
    name: 'file-down',
    label: 'File download',
    category: 'files',
    keywords: ['save', 'get', 'document'],
  },
  {
    name: 'file-up',
    label: 'File upload',
    category: 'files',
    keywords: ['put', 'send', 'document'],
  },
  {
    name: 'file-pen',
    label: 'Edit file',
    category: 'files',
    keywords: ['write', 'modify', 'document'],
  },
  {
    name: 'file-key',
    label: 'Key file',
    category: 'files',
    keywords: ['secret', 'credential', 'certificate'],
  },
  {
    name: 'file-exclamation-point',
    label: 'File warning',
    category: 'files',
    keywords: ['issue', 'alert', 'document'],
  },
  {
    name: 'file-chart-column',
    label: 'Report file',
    category: 'files',
    keywords: ['report', 'chart', 'document'],
  },
  {
    name: 'file-image',
    label: 'Image file',
    category: 'files',
    keywords: ['picture', 'photo', 'document'],
  },
  {
    name: 'file-play',
    label: 'Video file',
    category: 'files',
    keywords: ['movie', 'clip', 'document'],
  },
  {
    name: 'file-headphone',
    label: 'Audio file',
    category: 'files',
    keywords: ['sound', 'music', 'document'],
  },
  {
    name: 'file-archive',
    label: 'Archive file',
    category: 'files',
    keywords: ['zip', 'compressed', 'document'],
  },
  {
    name: 'file-terminal',
    label: 'Script file',
    category: 'files',
    keywords: ['shell', 'cli', 'document'],
  },
  { name: 'folder', label: 'Folder', category: 'files', keywords: ['directory', 'files', 'group'] },
  {
    name: 'briefcase',
    label: 'Briefcase',
    category: 'business',
    keywords: ['work', 'job', 'business'],
  },
  {
    name: 'building',
    label: 'Building',
    category: 'business',
    keywords: ['office', 'company', 'site'],
  },
  {
    name: 'building-complex',
    label: 'Offices',
    category: 'business',
    keywords: ['company', 'hq', 'towers'],
  },
  {
    name: 'landmark',
    label: 'Bank',
    category: 'business',
    keywords: ['finance', 'institution', 'government'],
  },
  { name: 'store', label: 'Store', category: 'business', keywords: ['shop', 'retail', 'market'] },
  {
    name: 'factory',
    label: 'Factory',
    category: 'business',
    keywords: ['plant', 'industry', 'manufacturing'],
  },
  { name: 'hotel', label: 'Hotel', category: 'business', keywords: ['lodging', 'stay', 'travel'] },
  {
    name: 'house',
    label: 'House',
    category: 'business',
    keywords: ['home', 'residence', 'property'],
  },
  {
    name: 'house-plug',
    label: 'Smart home',
    category: 'business',
    keywords: ['home', 'energy', 'iot'],
  },
  { name: 'tent', label: 'Tent', category: 'business', keywords: ['camp', 'temporary', 'outdoor'] },
  {
    name: 'credit-card',
    label: 'Credit card',
    category: 'business',
    keywords: ['payment', 'pay', 'card'],
  },
  { name: 'wallet', label: 'Wallet', category: 'business', keywords: ['money', 'pay', 'funds'] },
  {
    name: 'banknote',
    label: 'Banknote',
    category: 'business',
    keywords: ['cash', 'money', 'bill'],
  },
  { name: 'coins', label: 'Coins', category: 'business', keywords: ['money', 'cash', 'change'] },
  {
    name: 'piggy-bank',
    label: 'Savings',
    category: 'business',
    keywords: ['bank', 'money', 'fund'],
  },
  {
    name: 'receipt',
    label: 'Receipt',
    category: 'business',
    keywords: ['invoice', 'bill', 'proof'],
  },
  {
    name: 'receipt-text',
    label: 'Invoice',
    category: 'business',
    keywords: ['bill', 'receipt', 'charge'],
  },
  {
    name: 'shopping-cart',
    label: 'Shopping cart',
    category: 'business',
    keywords: ['basket', 'checkout', 'buy'],
  },
  {
    name: 'shopping-bag',
    label: 'Shopping bag',
    category: 'business',
    keywords: ['purchase', 'retail', 'buy'],
  },
  {
    name: 'shopping-basket',
    label: 'Shopping basket',
    category: 'business',
    keywords: ['purchase', 'retail', 'buy'],
  },
  { name: 'tag', label: 'Tag', category: 'business', keywords: ['label', 'price', 'category'] },
  {
    name: 'tags',
    label: 'Tags',
    category: 'business',
    keywords: ['labels', 'categories', 'prices'],
  },
  { name: 'ticket', label: 'Ticket', category: 'business', keywords: ['pass', 'support', 'entry'] },
  {
    name: 'ticket-check',
    label: 'Valid ticket',
    category: 'business',
    keywords: ['approved', 'pass', 'entry'],
  },
  {
    name: 'ticket-percent',
    label: 'Coupon',
    category: 'business',
    keywords: ['discount', 'voucher', 'deal'],
  },
  { name: 'clock', label: 'Clock', category: 'business', keywords: ['time', 'hour', 'schedule'] },
  {
    name: 'package',
    label: 'Package',
    category: 'logistics',
    keywords: ['parcel', 'box', 'shipment'],
  },
  {
    name: 'package-check',
    label: 'Package delivered',
    category: 'logistics',
    keywords: ['parcel', 'done', 'received'],
  },
  {
    name: 'package-open',
    label: 'Open package',
    category: 'logistics',
    keywords: ['parcel', 'unpack', 'received'],
  },
  {
    name: 'package-plus',
    label: 'Add package',
    category: 'logistics',
    keywords: ['parcel', 'new', 'stock'],
  },
  {
    name: 'package-minus',
    label: 'Remove package',
    category: 'logistics',
    keywords: ['parcel', 'pick', 'stock'],
  },
  {
    name: 'package-x',
    label: 'Package issue',
    category: 'logistics',
    keywords: ['parcel', 'failed', 'lost'],
  },
  {
    name: 'truck',
    label: 'Truck',
    category: 'logistics',
    keywords: ['delivery', 'shipping', 'lorry'],
  },
  {
    name: 'truck-electric',
    label: 'Electric truck',
    category: 'logistics',
    keywords: ['delivery', 'ev', 'shipping'],
  },
  {
    name: 'forklift',
    label: 'Forklift',
    category: 'logistics',
    keywords: ['warehouse', 'lift', 'pallet'],
  },
  {
    name: 'warehouse',
    label: 'Warehouse',
    category: 'logistics',
    keywords: ['storage', 'depot', 'stock'],
  },
  { name: 'ship', label: 'Ship', category: 'logistics', keywords: ['vessel', 'sea', 'freight'] },
  { name: 'sailboat', label: 'Sailboat', category: 'logistics', keywords: ['boat', 'sea', 'sail'] },
  { name: 'anchor', label: 'Anchor', category: 'logistics', keywords: ['port', 'harbor', 'dock'] },
  { name: 'plane', label: 'Plane', category: 'logistics', keywords: ['air', 'flight', 'freight'] },
  {
    name: 'plane-takeoff',
    label: 'Departure',
    category: 'logistics',
    keywords: ['flight', 'takeoff', 'leave'],
  },
  {
    name: 'plane-landing',
    label: 'Arrival',
    category: 'logistics',
    keywords: ['flight', 'landing', 'arrive'],
  },
  {
    name: 'train-front',
    label: 'Train',
    category: 'logistics',
    keywords: ['rail', 'transit', 'freight'],
  },
  {
    name: 'train-track',
    label: 'Rail track',
    category: 'logistics',
    keywords: ['railway', 'line', 'route'],
  },
  {
    name: 'tram-front',
    label: 'Tram',
    category: 'logistics',
    keywords: ['rail', 'transit', 'city'],
  },
  {
    name: 'bus',
    label: 'Bus',
    category: 'logistics',
    keywords: ['transit', 'public', 'passenger'],
  },
  {
    name: 'bus-front',
    label: 'Bus front',
    category: 'logistics',
    keywords: ['transit', 'public', 'passenger'],
  },
  { name: 'car', label: 'Car', category: 'logistics', keywords: ['vehicle', 'auto', 'drive'] },
  {
    name: 'car-front',
    label: 'Car front',
    category: 'logistics',
    keywords: ['vehicle', 'auto', 'drive'],
  },
  { name: 'bike', label: 'Bike', category: 'logistics', keywords: ['bicycle', 'cycle', 'ride'] },
  {
    name: 'map-pin',
    label: 'Map pin',
    category: 'logistics',
    keywords: ['location', 'place', 'marker'],
  },
  {
    name: 'circle-check',
    label: 'Success',
    category: 'status-shapes',
    keywords: ['ok', 'done', 'passed'],
  },
  {
    name: 'circle-check-big',
    label: 'Check circle',
    category: 'status-shapes',
    keywords: ['ok', 'done', 'passed'],
  },
  {
    name: 'circle-x',
    label: 'Failed',
    category: 'status-shapes',
    keywords: ['error', 'cancel', 'close'],
  },
  {
    name: 'circle-alert',
    label: 'Alert',
    category: 'status-shapes',
    keywords: ['warning', 'attention', 'notice'],
  },
  {
    name: 'circle-question-mark',
    label: 'Help',
    category: 'status-shapes',
    keywords: ['question', 'unknown', 'support'],
  },
  {
    name: 'circle-pause',
    label: 'Paused',
    category: 'status-shapes',
    keywords: ['hold', 'wait', 'stopped'],
  },
  {
    name: 'circle-play',
    label: 'Running',
    category: 'status-shapes',
    keywords: ['play', 'start', 'active'],
  },
  {
    name: 'circle-stop',
    label: 'Stopped',
    category: 'status-shapes',
    keywords: ['halt', 'end', 'terminated'],
  },
  {
    name: 'circle-dot',
    label: 'Current step',
    category: 'status-shapes',
    keywords: ['active', 'here', 'state'],
  },
  {
    name: 'circle-dashed',
    label: 'Pending',
    category: 'status-shapes',
    keywords: ['todo', 'placeholder', 'empty'],
  },
  {
    name: 'circle-slash',
    label: 'Disabled',
    category: 'status-shapes',
    keywords: ['forbidden', 'none', 'skip'],
  },
  {
    name: 'circle-minus',
    label: 'Minus circle',
    category: 'status-shapes',
    keywords: ['remove', 'subtract', 'less'],
  },
  {
    name: 'circle-plus',
    label: 'Plus circle',
    category: 'status-shapes',
    keywords: ['add', 'more', 'create'],
  },
  {
    name: 'circle-arrow-right',
    label: 'Next',
    category: 'status-shapes',
    keywords: ['forward', 'continue', 'go'],
  },
  {
    name: 'circle-arrow-left',
    label: 'Previous',
    category: 'status-shapes',
    keywords: ['back', 'return', 'go'],
  },
  {
    name: 'circle-arrow-up',
    label: 'Up',
    category: 'status-shapes',
    keywords: ['raise', 'increase', 'top'],
  },
  {
    name: 'circle-arrow-down',
    label: 'Down',
    category: 'status-shapes',
    keywords: ['lower', 'decrease', 'bottom'],
  },
  {
    name: 'circle-ellipsis',
    label: 'In progress',
    category: 'status-shapes',
    keywords: ['more', 'loading', 'working'],
  },
  {
    name: 'circle-gauge',
    label: 'Level',
    category: 'status-shapes',
    keywords: ['meter', 'gauge', 'measure'],
  },
  {
    name: 'circle-power',
    label: 'Power button',
    category: 'status-shapes',
    keywords: ['on', 'off', 'toggle'],
  },
  {
    name: 'square-check',
    label: 'Checkbox',
    category: 'status-shapes',
    keywords: ['done', 'tick', 'task'],
  },
  {
    name: 'square-x',
    label: 'Cancelled',
    category: 'status-shapes',
    keywords: ['close', 'remove', 'reject'],
  },
  {
    name: 'square-minus',
    label: 'Square minus',
    category: 'status-shapes',
    keywords: ['remove', 'indeterminate', 'less'],
  },
  {
    name: 'triangle-alert',
    label: 'Warning',
    category: 'status-shapes',
    keywords: ['alert', 'caution', 'danger'],
  },
  {
    name: 'diamond',
    label: 'Diamond',
    category: 'status-shapes',
    keywords: ['decision', 'rhombus', 'gateway'],
  },
  {
    name: 'shapes',
    label: 'Shapes',
    category: 'status-shapes',
    keywords: ['geometry', 'figures', 'primitives'],
  },
  {
    name: 'search',
    label: 'Search',
    category: 'status-shapes',
    keywords: ['find', 'magnifier', 'lookup'],
  },
];
