import { describe, expect, it } from 'vitest';

import { prepareStatement, stripCasts } from './prepare-statement';

describe('prepareStatement (research R3)', () => {
  it('replaces column types by text and keeps the originals in order', () => {
    const { text, columns } = prepareStatement(
      "CREATE TABLE t (\n  status public.order_status NOT NULL,\n  at timestamp(3) with time zone,\n  n character varying(20) DEFAULT 'x',\n  bare,\n  CONSTRAINT pk PRIMARY KEY (status)\n)",
      10,
    );
    expect(text).toBe(
      'CREATE TABLE t (\n  "status" text NOT NULL,\n  "at" text,\n  "n" text DEFAULT \'x\',\n  "bare",\n  CONSTRAINT pk PRIMARY KEY (status)\n)',
    );
    expect(columns).toEqual([
      { name: 'status', type: 'public.order_status', line: 11, dropped: [] },
      { name: 'at', type: 'timestamp(3) with time zone', line: 12, dropped: [] },
      { name: 'n', type: 'character varying(20)', line: 13, dropped: [] },
      { name: 'bare', type: '', line: 14, dropped: [] },
    ]);
  });

  it('reads GENERATED ALWAYS AS IDENTITY as BY DEFAULT', () => {
    const { text } = prepareStatement(
      'CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY (START WITH 1))',
      1,
    );
    expect(text).toBe('CREATE TABLE t ("id" text GENERATED BY DEFAULT AS IDENTITY)');
  });

  it('removes generated expressions and reports them', () => {
    const { text, columns } = prepareStatement(
      'CREATE TABLE t (a int, b int GENERATED ALWAYS AS (a * 2) STORED)',
      1,
    );
    expect(text).toBe('CREATE TABLE t ("a" text, "b" text )');
    expect(columns[1]?.dropped).toEqual(['generated expression']);
  });

  it('strips casts outside quotes, qualified or not', () => {
    expect(stripCasts("DEFAULT 'a'::public.order_status")).toBe("DEFAULT 'a'");
    expect(stripCasts("CHECK ((price >= (0)::numeric)) AND x = 'a::b'")).toBe(
      "CHECK ((price >= (0))) AND x = 'a::b'",
    );
    expect(stripCasts("DEFAULT '{}'::text[]")).toBe("DEFAULT '{}'");
    expect(stripCasts('x::character varying(20)')).toBe('x');
  });

  it('keeps MySQL index and key definitions as constraints, and a column named key as a column', () => {
    const { text, columns } = prepareStatement(
      'CREATE TABLE t (`key` varchar(10), KEY `k` (`key`), UNIQUE KEY `u` (`key`), n int)',
      1,
      'mysql',
    );
    expect(columns.map((c) => c.name)).toEqual(['key', 'n']);
    expect(text).toBe(
      'CREATE TABLE t (`key` text, KEY `k` (`key`), UNIQUE KEY `u` (`key`), `n` text)',
    );
  });

  it('reads columns added by ALTER TABLE', () => {
    const { text, columns } = prepareStatement(
      'ALTER TABLE ONLY public.t ADD COLUMN note mood NOT NULL, ADD COLUMN IF NOT EXISTS b int',
      3,
    );
    expect(text).toBe(
      'ALTER TABLE ONLY public.t ADD COLUMN "note" text NOT NULL, ADD COLUMN IF NOT EXISTS "b" text',
    );
    expect(columns.map((c) => [c.name, c.type])).toEqual([
      ['note', 'mood'],
      ['b', 'int'],
    ]);
  });

  it('leaves other statements as they are, casts aside', () => {
    expect(prepareStatement("COMMENT ON TABLE t IS 'x'", 1)).toEqual({
      text: "COMMENT ON TABLE t IS 'x'",
      columns: [],
    });
  });
});
