import { describe, expect, it } from 'vitest';

import { edgeCaseDeck, edgeCaseRequest, nameClashDeck } from '../fixtures/export-edge-cases';
import { shopDeck } from '../fixtures/shop';
import { schemaExport } from './schema-export';
import { DEFAULT_SQL_OPTIONS, type SqlDialect, type SqlOptions } from './types';

const DIALECTS: readonly SqlDialect[] = ['postgres', 'mysql', 'sqlite'];

function shopSql(dialect: SqlDialect, sql: Partial<SqlOptions> = {}): string {
  return schemaExport(shopDeck(dialect), {
    format: 'sql',
    scope: { kind: 'deck' },
    dialect: null,
    sql: { ...DEFAULT_SQL_OPTIONS, ...sql },
  }).text;
}

/** The statement that creates `table`, up to its closing `);`. */
function createStatement(text: string, table: string): string {
  const start = text.indexOf(`CREATE TABLE ${table} (`);
  if (start === -1) throw new Error(`no CREATE TABLE ${table}`);
  return text.slice(start, text.indexOf(';', start) + 1);
}

describe('writeSql golden files', () => {
  it.each(DIALECTS)('writes the Shop deck (%s)', async (dialect) => {
    await expect(shopSql(dialect)).toMatchFileSnapshot(`./__golden__/sql/shop.${dialect}.sql`);
  });

  it.each(DIALECTS)('writes the edge cases (%s)', async (dialect) => {
    const { text } = schemaExport(edgeCaseDeck(), edgeCaseRequest('sql', dialect));
    await expect(text).toMatchFileSnapshot(`./__golden__/sql/edge-cases.${dialect}.sql`);
  });

  it.each(DIALECTS)('writes the name clash (%s)', async (dialect) => {
    const { text } = schemaExport(nameClashDeck(), {
      format: 'sql',
      scope: { kind: 'deck' },
      dialect,
      sql: DEFAULT_SQL_OPTIONS,
    });
    await expect(text).toMatchFileSnapshot(`./__golden__/sql/name-clash.${dialect}.sql`);
  });
});

describe('writeSql', () => {
  it('starts with the deck, scope and dialect', () => {
    expect(shopSql('postgres').split('\n')[0]).toBe('-- Shop · Whole deck · Postgres');
    expect(shopSql('mysql').split('\n')[1]).toBe('-- Generated by Sododeck. Notes: 0');
  });

  it('creates a referenced table before the table that references it', () => {
    for (const dialect of DIALECTS) {
      const text = shopSql(dialect);
      expect(text.indexOf('CREATE TABLE customers')).toBeLessThan(
        text.indexOf('CREATE TABLE orders'),
      );
      expect(text).toContain('REFERENCES customers (id) ON DELETE CASCADE');
    }
  });

  it('places foreign keys per dialect', () => {
    expect(createStatement(shopSql('postgres'), 'orders')).toContain(
      'customer_id uuid NOT NULL REFERENCES customers (id) ON DELETE CASCADE,',
    );
    expect(createStatement(shopSql('mysql'), 'orders')).toContain(
      'FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE',
    );
    expect(createStatement(shopSql('sqlite'), 'orders')).toContain(
      'customer_id text NOT NULL REFERENCES customers (id) ON DELETE CASCADE,',
    );
  });

  it('adds cycle foreign keys after the tables, except on SQLite', () => {
    const write = (dialect: SqlDialect) =>
      schemaExport(edgeCaseDeck(), edgeCaseRequest('sql', dialect)).text;
    expect(write('postgres')).toContain('ALTER TABLE a ADD FOREIGN KEY (b_id) REFERENCES b (id);');
    expect(write('mysql')).toContain('ALTER TABLE a ADD FOREIGN KEY (b_id) REFERENCES b (id);');
    expect(write('sqlite')).not.toContain('ALTER TABLE');
    expect(createStatement(write('sqlite'), 'a')).toContain('b_id integer REFERENCES b (id)');
  });

  it('keeps composite keys in stored order', () => {
    const text = createStatement(shopSql('postgres'), 'shipment_items');
    expect(text).toContain('PRIMARY KEY (shipment_id, order_id, product_id)');
    expect(text).toContain(
      'FOREIGN KEY (order_id, product_id) REFERENCES order_items (order_id, product_id)',
    );
  });

  it('writes enums per dialect', () => {
    const postgres = shopSql('postgres');
    expect(postgres.indexOf('CREATE TYPE order_status AS ENUM')).toBeLessThan(
      postgres.indexOf('CREATE TABLE orders'),
    );
    expect(createStatement(shopSql('mysql'), 'orders')).toContain(
      "status enum('pending', 'paid', 'shipped', 'cancelled') NOT NULL DEFAULT 'pending'",
    );
    expect(createStatement(shopSql('sqlite'), 'orders')).toContain(
      "status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'shipped', 'cancelled'))",
    );
  });

  it('quotes value defaults and writes expressions as typed (parenthesised on MySQL)', () => {
    expect(createStatement(shopSql('postgres'), 'customers')).toContain('DEFAULT now()');
    expect(createStatement(shopSql('mysql'), 'customers')).toContain('DEFAULT (now())');
    expect(createStatement(shopSql('sqlite'), 'customers')).toContain('DEFAULT CURRENT_TIMESTAMP');
    expect(createStatement(shopSql('sqlite'), 'products')).toContain('DEFAULT 1');
    expect(createStatement(shopSql('postgres'), 'products')).toContain('DEFAULT TRUE');
  });

  it('creates or drops schemas per dialect', () => {
    const write = (dialect: SqlDialect) =>
      schemaExport(edgeCaseDeck(), edgeCaseRequest('sql', dialect));
    expect(write('postgres').text).toContain('CREATE SCHEMA IF NOT EXISTS billing;');
    expect(write('postgres').text).toContain('CREATE TABLE billing.ledgers (');
    expect(write('mysql').text).toContain('CREATE DATABASE IF NOT EXISTS billing;');
    const sqlite = write('sqlite');
    expect(sqlite.text).toContain('CREATE TABLE ledgers (');
    expect(sqlite.notes.map((n) => n.kind)).toContain('schema-dropped');
  });

  it('quotes reserved and mixed-case names per dialect', () => {
    const write = (dialect: SqlDialect) =>
      schemaExport(edgeCaseDeck(), edgeCaseRequest('sql', dialect)).text;
    expect(write('postgres')).toContain(
      'CREATE TABLE "order" (\n  id integer PRIMARY KEY,\n  "UserId" integer',
    );
    expect(write('mysql')).toContain('CREATE TABLE `order items` (');
  });

  it('writes auto-increment in the dialect form', () => {
    expect(shopSql('postgres')).toContain(
      'id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,',
    );
    expect(shopSql('mysql')).toContain('id int AUTO_INCREMENT PRIMARY KEY,');
    expect(shopSql('sqlite')).toContain('id integer PRIMARY KEY AUTOINCREMENT,');
  });

  describe('options', () => {
    it('leaves out enum types and indexes', () => {
      const result = schemaExport(shopDeck('postgres'), {
        format: 'sql',
        scope: { kind: 'deck' },
        dialect: null,
        sql: { ...DEFAULT_SQL_OPTIONS, enumsAndIndexes: false },
      });
      expect(result.text).not.toContain('CREATE TYPE');
      expect(result.text).not.toContain('CREATE INDEX');
      expect(result.text).toContain('status order_status NOT NULL');
      expect(result.notes.map((n) => n.kind)).toEqual(['enum-not-created']);
      // MySQL and SQLite enums are inline, so they stay.
      expect(shopSql('mysql', { enumsAndIndexes: false })).toContain("status enum('pending'");
    });

    it('skips n–n relationships when junction tables are off', () => {
      const result = schemaExport(shopDeck('postgres'), {
        format: 'sql',
        scope: { kind: 'deck' },
        dialect: null,
        sql: { ...DEFAULT_SQL_OPTIONS, junctionTables: false },
      });
      expect(result.text).not.toContain('products_categories');
      expect(result.notes).toEqual([
        expect.objectContaining({
          kind: 'junction-skipped',
          message: 'products ↔ categories (n–n) not written: junction tables are off',
        }),
      ]);
      expect(result.text).toContain('-- products ↔ categories (n–n) not written');
    });

    it('adds IF NOT EXISTS where the dialect has it', () => {
      expect(shopSql('postgres', { ifNotExists: true })).toContain(
        'CREATE TABLE IF NOT EXISTS customers (',
      );
      expect(shopSql('postgres', { ifNotExists: true })).toContain(
        'CREATE INDEX IF NOT EXISTS customers_email_lower_idx',
      );
      expect(shopSql('mysql', { ifNotExists: true })).toContain(
        'CREATE INDEX customers_email_lower_idx',
      );
      expect(shopSql('sqlite')).not.toContain('IF NOT EXISTS');
    });
  });

  describe('junction tables', () => {
    it('names the table and its columns from both sides', () => {
      const text = createStatement(shopSql('postgres'), 'products_categories');
      expect(text).toBe(
        [
          'CREATE TABLE products_categories (',
          '  products_id uuid REFERENCES products (id),',
          '  categories_id uuid REFERENCES categories (id),',
          '  PRIMARY KEY (products_id, categories_id)',
          ');',
        ].join('\n'),
      );
      const all = shopSql('postgres');
      expect(all).toContain('-- n-n products ↔ categories\nCREATE TABLE products_categories');
      expect(all.indexOf('CREATE TABLE products_categories')).toBeGreaterThan(
        all.indexOf('CREATE TABLE products ('),
      );
    });

    it('adds a suffix on a name clash and for a self n–n', () => {
      const result = schemaExport(edgeCaseDeck(), edgeCaseRequest('sql', 'postgres'));
      expect(result.text).toContain('CREATE TABLE products_categories_2 (');
      expect(result.text).toContain('  tags_id_2 integer REFERENCES tags (id),');
      expect(result.notes.map((n) => n.kind)).toEqual(
        expect.arrayContaining(['junction-renamed', 'self-junction', 'no-key']),
      );
    });
  });

  it('is deterministic', () => {
    expect(shopSql('mysql')).toBe(shopSql('mysql'));
    expect(shopSql('mysql').endsWith(');\n')).toBe(true);
  });
});
